apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - argo.gitlab.be
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q0lXQkEyZmtDbVNrY3B4
        bGwvTVRuZEZkZHRyZHJLZFY2YXBNTUJwOGg0CmFMRk5qR1FDc2NTRU9sY0JST2tQ
        NnNYZFlzY01JK2pSQlJzVWhXUi96UTgKLS0tIGVSTEJXajVMbkFJMzBRcWpmSWNK
        MEV1UmFvZTNBaDZ6dk5Sb1VOUjhBcVEKbAOEgBT7bhT4zmnG2eYoCF6jX/M73ImX
        8VmI8JZp152wMTrV+DXBy2MPzn+2pwrFjFUCIaiVzecZu03An5Kaog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T15:52:03Z"
  mac: ENC[AES256_GCM,data:B3qJfuGRWcmSLJYRl5s+oPzURUNWVf61dOiGFhCa1BM5Rbd3kjkGkdGg4egyckVtrkzrKtyQuSrKyhckawNm6sYKkg6hZlpCdUsJS3N26sYUxuUnEKStLhYr0tnjHiNd/n7ecsWOG3HgDUf40td4XVjXQ+kzayWh4GNasG2itGM=,iv:YGabkTeTU/U4czP4mnHJUdNQaIo7+JZ/N9YWyLkM4Q4=,tag:Fan+QPTFTCzKDhYlBG3kOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
