apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - argo.gitlab.be
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRnNDZWYzNTU3MUdkbGJL
        Rytsc2UxSVRBZUdUQnRoWjYrQzl3VjFxQ1ZVCnlLSEVjUmw3bVluQlF4cWhFRHpk
        K2Vsd1ZBa0dHUHo2K2J2NHZFOUU2cDQKLS0tIEsxWmdVajZubUlZQk8vV0JGa2RO
        eVpRNnhWbFFneE43VXdEL0Z6Mm0vb00K6MoiXnhvDPNdSg+Tdbxjv7zmlHtw2prK
        Bs6DX9oDdAV9iUDPTG/rK5oxMVgkLebeTbKZJBz2+D+fwIRfn1n3Rg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T20:00:43Z"
  mac: ENC[AES256_GCM,data:P0SO8COVht+36Z0JYe/qo9legA7LP200s5Bp7CeYRm7BvPSbOLPiuz3qeCMuV3uaaFkbHEj6qFTSLHGeri8+LVQ+bo6r/rQLTfqMlMRMLO+ffurJsxoTr2jYj21Auk3lpEgpR+2M0zW9Ne7M4z47Va6NljSXeema0/iZ/7Yrf/U=,iv:J4pw9KCRC5Ork7qHP/kzTcFklgdja6twPBNmkBn+CRs=,tag:irUC5cIfhfLm84G71FdGaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
