apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
  hostnames:
    - argo.gitlab.be
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbk4ybEluNWljclluNFVP
        THhDWmgxb29RSGlzL3NZaFpoaGNxV0tNeVRvCjFOUGpKdGxzdG5oYWpKTWRiRnF2
        R2tzcHJKRWhtNGJqZXhFeHpCdTF6M1EKLS0tIEZObjRORmxSUkc2MzJtc0Eva0JZ
        VHVwQjJLVi8wVDlIUS82RGNPU2RZTnMKR8hNvwZJDxTRMFOucCsQvX96XlgIy+u5
        BOuuqQ7KLZ9FOo0fsmXBBFqRna++Xnmr8HpiyZwuU7hCzR9MVXrd2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T15:39:16Z"
  mac: ENC[AES256_GCM,data:l0pMAQL29a0AlpJeSd1brXs3Lz5Ip6c0ttx7qD8tTWJW2aZfR3PzmrLjHjyK3IpNU9HRzSCCGQShey8jNXkaaXA2DAwc+8sAOsOsMDDXCswez9joDBC1rMYV3mSom3QL8NTZoh4p8yWhCp7rD8qvDutzfg3HV3CcagIik6NuopE=,iv:cFVIZwxwYC3iepYAav7LHGVVOGHhChBf51RuT9Q2IXM=,tag:MDvxTdplhoR0IijUXlvP3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
