apiVersion: v1
kind: Secret
metadata:
  name: healthtracking-db
  namespace: home
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:MdHex4IquiZaFDhlP5IOFl/d4MGIdwDhAahplE3BZC3EUA==,iv:7u56MB4itG27SER+hpW4n0vHL+GFurZO9pXeY4GwR0M=,tag:10K7jbpxDrr/luszE/AXHQ==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM0c1SlZreHVuSjFZRXNj
        NDRzaGtmME5qVHlSUDNCSy9UYmtlZmkvcG5jCkhnWXcrS1R3L1VSd2pYaS93MEJ2
        YTZYVHpvWVM5VDY3OTBOMU1ubllheFUKLS0tIDZKemMzN0RFVGp5dk9RN2VFcWds
        N2pSRDZwODhxaTlmWnpySVc5NU51VnMKugrVO33C7uGul8weLdMax19bJ+YCZk4Y
        4Kr4PMy8jIxVA1VFdrqlVGhVEax8Ok4K1YqimcklJpMprc/p0iTPRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T15:57:47Z"
  mac: ENC[AES256_GCM,data:kfA1dGoqPIjX1njAMMQpIBwqt3xtxKtATGpMqFoJyMZ0xYZ79FYbm8qbtk9hR9ROE7qUzsbhZB5w06T7RvAtAzpqLBn57Ye1uFGqgK39Ty73sUta/G8kVf9agTw9oED/pBFZ28pMKpsNRAZ/GmeAbTATx2Q/Nuu9qKNfQe8LyOI=,iv:01c42CxOxxoVcbPKMtN2j4WfbX3CQnpZStP+dp4ZraQ=,tag:FsfC21A0pQrKabfH0oqBvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
