apiVersion: v1
kind: Secret
metadata:
  name: healthtracking-db
  namespace: home
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:mIu/SmLcKcgrxzFVDD/07OimCTL3Saj0zXSKgQ==,iv:Y/3HubzE2rQn2ayMoiV9ol87dsdMnUQqt1yd5JIZHH0=,tag:i2GXWSFrdhXrIH4Ke5uibA==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMHE1N3RQeDFDQkFpYkVE
        TGkwYzl0c1R1L2J6NXBUclZpVWFHZkZWTkJFCklzN3F1VWp5QUpXakdlMFhOc3F1
        Zlg5UnlWZG5RVk1vTThBWEdWa1pyZUEKLS0tIFFDUmYyTXFNTk4yaFRHUVg0RFNX
        VktJVDhnRm9BZFpHS013YkpheGdZWlEKz47RTEXuje0jFQsYkiSy4LbFwGY3GqxM
        5/sUIYCQ9nBb7toXuwGN1JToflprTxt1AYatU9F8wBHGjH43C7uQOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T20:07:56Z"
  mac: ENC[AES256_GCM,data:9w1OzF8xu7C2ou1R0KklApaSTbVrxC1QqogM6XLWOWykhS33tNi/IOYXNfSemG7oqRLBB2eP8JHmxTgzQL36BotTnBldFMperFuAPWn6Zh0uV3P8GN/V1Bbt0GUqU/lVpLcwYQb5I0ELzVBBI08EhCqdf+ecs5RD588gGKycy+Q=,iv:dzTtjGVTLZEHJ+4dMfSqsp22W4OfAC1fq/rnvh2ci6U=,tag:Fl8IwevWWkQAtL8Hen/P8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
