apiVersion: v1
kind: Secret
metadata:
  name: healthtracking-db
  namespace: home
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:7Rk3LBp3Zqh3SiRoOtxW95+EtNeWP4rSy7N4eg==,iv:V2Qn2pkbIyYckmiQSoU1y75CCsD/Bs5jCtWl8w+v3IY=,tag:CdWYohBW60Qp9KesOGJvOQ==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRStJNHQ1d2oydnZRaElo
        K0ZHbGJBeFA5ekV3SXhkNUhCQlpaU1UxdENZCmhjbkRtdDBXNGxGQkN5YWw2VzlR
        THNoK0JUTTRmUmNGZ2hkdXhIZjZ2UlkKLS0tIDVwM0hvSzRzbVNZbDFKV1lNaldv
        aTkwQWd6czFOTnJ3bnlRWXpJait6aWcKae2eLlWbZr+Iz+sx5+9fguZaboMwugRu
        HddClQDyCFTE/ATy1sRF+1wFllNDr4Dvek3eE5ZI+lwpVefDGH6ung==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T21:19:36Z"
  mac: ENC[AES256_GCM,data:a8zyddY9PjkVvJLX4aQEIzlIJJxNHRpBl40xNAZ8dAYO2+nKGXTLQ/FYMdiVGiUIAkGW4UKaJbUq3MYnmmQMjosLg0EJ+LxEDpDh7G0DrNyMKV3TgVN/IIdWdwxlpLxGCt0Q0rRTjVCVRIOFvkDrEbf8oi3jWFDZIU4nGxEJUeA=,iv:tqkqw77AESwOMh42WGTFYg22sXKcPm61cJY8+0xwbkI=,tag:p1mLDXMCUL+Jl/egU1xWow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
