apiVersion: batch/v1
kind: Job
metadata:
  name: restart-envoy-gateway
  namespace: network
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: restart-envoy-gateway
      restartPolicy: Never
      containers:
      - name: restart
        image: bitnami/kubectl:latest
        command:
        - sh
        - -c
        - kubectl delete pod -n network -l app.kubernetes.io/name=envoy-gateway
