apiVersion: v1
kind: ServiceAccount
metadata:
  name: restart-envoy-gateway
  namespace: network
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-envoy-gateway
  namespace: network
rules:
- apiGroups: ["apps"]
  resources: ["deployments/rollout"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-envoy-gateway
  namespace: network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-envoy-gateway
subjects:
- kind: ServiceAccount
  name: restart-envoy-gateway
  namespace: network
