apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-be-production
spec:
  dnsNames:
    - gitlab.be
    - '*.gitlab.be'
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: gitlab-be-production-tls
  usages:
    - digital signature
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb0pJV1VNNGU4NytCSDhE
        TFpaUDZVd3hncTNMTEdKYVZuaEZiSURodTBRCmg4VlZsdFc1QTF5RmQ5MkV2ZXJY
        b3UvK1FvSkcxUEdiaCs3QUd0NzhQVUkKLS0tIGlvd3FGU2p2MTNZM3ZyeWhnd3VR
        Q0Vwb2wyTks3RUFMK2ZsZFp4aEg5QjgKQcg+Duz5fockVLUOY0b4Xw3DsHN4LJzP
        DFrweExj6iCT2g1fnu+fMPrpXg7+wMpUcgNJCW9NDs4scXiKczYcMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T20:37:26Z"
  mac: ENC[AES256_GCM,data:CScKoX4vNV54ctmK6B4iUuRLlX6Ig+Sl9RRSEmzwT2NBX1NYm2IGL96hAXp+nhkPB7JFr+M26AfjWcE+1aKD9z3Xwdk61kM1OifRbWPL0vju3zowC03UW72S36H4C+uktJ86z5PYdJd6TnSSNn1DI4/NVdNPWTWxcJvpKcGYLCc=,iv:YU+HZfp7ipOyI2IMMebZr88Gyo8Y5kEz9ErbydvvAIA=,tag:Pgew7/dEi+Lr8YPQZuNK+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
