apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-be-production
spec:
  dnsNames:
    - gitlab.be
    - '*.gitlab.be'
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: gitlab-be-production-tls
  usages:
    - digital signature
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOWN4cVJtWHltcXlJalc2
        UXp3WkxnUm8vMCtob25jZ3NHeklMU2I1bFI4CnpVQzVBeldIV3E3VERNS0dLT2ho
        SmpqR0haYk0xQmo5bUZkSzR0OVFiUWMKLS0tIFBydTVyUE1jWXY1WTlSRjNURUdE
        eUxGZDJDNVlJeUdUN2c5dyswRUE5dTgKf+6ABHb1vh/ec7PCT9rT1WeoyQRYcrCU
        41048jMD0RU2qShoGdai1o44oaY+KOAeYzwbn9WJV9XI1PVnwV2dEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T08:22:22Z"
  mac: ENC[AES256_GCM,data:4nY3+BwA3ht7QlEmHLzVO5sFlp6t56vmSHIGu6Oms69fyXJwxpVadn/3tBo9ar+P+nmtlsirwgYnU9JkYCOqogtQl0yYv2d/FdC+XiKFj8z9m7HKVlOlYir9Z+/a0mg1ib6ufA5Y/NRIoLGhhwwlmgJvJBRiHt25C1sWVhwgqmY=,iv:JG+X+WW9d2ZlWgJXjkxmeoAgvl9YSTiE0CoQmrdkGdA=,tag:v0mO8ikiMF97QKKQTuvQnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
