apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        externalTrafficPolicy: Cluster
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Zstd
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WUVYR2JpR3NCRkwva0tY
        TUtVbmtaK280Z3M5Zkowd2c0Qmg0eU1hTnhJCjFaZ3NRSXdDby9vRm9rSzZQZ0VB
        bGZDekF5U052N3JnVHZ1ZU8zcms2cm8KLS0tICtXRlBJK2xreG9JR0t1WmlKWndw
        aUJJNmFWVmU0Slp2TWxFdnRwRlljK0UKXeOYKQ1b/2/lksYrA9MYSIcRW2DnmgTy
        4D+U3iBNkRwJiouxFLQhw9V58kUf5pGlyOwaoTWQU+37TI8pthFH4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T19:31:57Z"
  mac: ENC[AES256_GCM,data:YORy5aGPwRFWTFSulfn5J4crz5P1A0BK4QvukvdhP6KNNDGjoerdMZ2ICuiTE0xFSi/qWvtS7Ly2XoaagO6Y4iSskwrC1qauKb+aGA8HmZrlVxJvX/bFiz+/KHC+Psutqw5eqXqjN0aX9IxycVn/NryOXpeJwteph1pfxXb6q8g=,iv:0BJ2ziTFskxZJv0C6VaXx5sAQOxaYzIMmhePsklIAeI=,tag:rT29x6f50aDmc/Ger6kF1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy
    namespace: network
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WUVYR2JpR3NCRkwva0tY
        TUtVbmtaK280Z3M5Zkowd2c0Qmg0eU1hTnhJCjFaZ3NRSXdDby9vRm9rSzZQZ0VB
        bGZDekF5U052N3JnVHZ1ZU8zcms2cm8KLS0tICtXRlBJK2xreG9JR0t1WmlKWndw
        aUJJNmFWVmU0Slp2TWxFdnRwRlljK0UKXeOYKQ1b/2/lksYrA9MYSIcRW2DnmgTy
        4D+U3iBNkRwJiouxFLQhw9V58kUf5pGlyOwaoTWQU+37TI8pthFH4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T19:31:57Z"
  mac: ENC[AES256_GCM,data:YORy5aGPwRFWTFSulfn5J4crz5P1A0BK4QvukvdhP6KNNDGjoerdMZ2ICuiTE0xFSi/qWvtS7Ly2XoaagO6Y4iSskwrC1qauKb+aGA8HmZrlVxJvX/bFiz+/KHC+Psutqw5eqXqjN0aX9IxycVn/NryOXpeJwteph1pfxXb6q8g=,iv:0BJ2ziTFskxZJv0C6VaXx5sAQOxaYzIMmhePsklIAeI=,tag:rT29x6f50aDmc/Ger6kF1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-external
  annotations:
    external-dns.alpha.kubernetes.io/target: external.gitlab.be
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: external.gitlab.be
      lbipam.cilium.io/ips: 192.168.1.23
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: gitlab-be-production-tls
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WUVYR2JpR3NCRkwva0tY
        TUtVbmtaK280Z3M5Zkowd2c0Qmg0eU1hTnhJCjFaZ3NRSXdDby9vRm9rSzZQZ0VB
        bGZDekF5U052N3JnVHZ1ZU8zcms2cm8KLS0tICtXRlBJK2xreG9JR0t1WmlKWndw
        aUJJNmFWVmU0Slp2TWxFdnRwRlljK0UKXeOYKQ1b/2/lksYrA9MYSIcRW2DnmgTy
        4D+U3iBNkRwJiouxFLQhw9V58kUf5pGlyOwaoTWQU+37TI8pthFH4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T19:31:57Z"
  mac: ENC[AES256_GCM,data:YORy5aGPwRFWTFSulfn5J4crz5P1A0BK4QvukvdhP6KNNDGjoerdMZ2ICuiTE0xFSi/qWvtS7Ly2XoaagO6Y4iSskwrC1qauKb+aGA8HmZrlVxJvX/bFiz+/KHC+Psutqw5eqXqjN0aX9IxycVn/NryOXpeJwteph1pfxXb6q8g=,iv:0BJ2ziTFskxZJv0C6VaXx5sAQOxaYzIMmhePsklIAeI=,tag:rT29x6f50aDmc/Ger6kF1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal.gitlab.be
      lbipam.cilium.io/ips: 192.168.1.24
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: gitlab-be-production-tls
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WUVYR2JpR3NCRkwva0tY
        TUtVbmtaK280Z3M5Zkowd2c0Qmg0eU1hTnhJCjFaZ3NRSXdDby9vRm9rSzZQZ0VB
        bGZDekF5U052N3JnVHZ1ZU8zcms2cm8KLS0tICtXRlBJK2xreG9JR0t1WmlKWndw
        aUJJNmFWVmU0Slp2TWxFdnRwRlljK0UKXeOYKQ1b/2/lksYrA9MYSIcRW2DnmgTy
        4D+U3iBNkRwJiouxFLQhw9V58kUf5pGlyOwaoTWQU+37TI8pthFH4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T19:31:57Z"
  mac: ENC[AES256_GCM,data:YORy5aGPwRFWTFSulfn5J4crz5P1A0BK4QvukvdhP6KNNDGjoerdMZ2ICuiTE0xFSi/qWvtS7Ly2XoaagO6Y4iSskwrC1qauKb+aGA8HmZrlVxJvX/bFiz+/KHC+Psutqw5eqXqjN0aX9IxycVn/NryOXpeJwteph1pfxXb6q8g=,iv:0BJ2ziTFskxZJv0C6VaXx5sAQOxaYzIMmhePsklIAeI=,tag:rT29x6f50aDmc/Ger6kF1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy
spec:
  compressor:
    - type: Zstd
      zstd: {}
    - type: Brotli
      brotli: {}
    - type: Gzip
      gzip: {}
  retry:
    numRetries: 2
    retryOn:
      triggers:
        - reset
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestTimeout: 0s
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WUVYR2JpR3NCRkwva0tY
        TUtVbmtaK280Z3M5Zkowd2c0Qmg0eU1hTnhJCjFaZ3NRSXdDby9vRm9rSzZQZ0VB
        bGZDekF5U052N3JnVHZ1ZU8zcms2cm8KLS0tICtXRlBJK2xreG9JR0t1WmlKWndw
        aUJJNmFWVmU0Slp2TWxFdnRwRlljK0UKXeOYKQ1b/2/lksYrA9MYSIcRW2DnmgTy
        4D+U3iBNkRwJiouxFLQhw9V58kUf5pGlyOwaoTWQU+37TI8pthFH4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T19:31:57Z"
  mac: ENC[AES256_GCM,data:YORy5aGPwRFWTFSulfn5J4crz5P1A0BK4QvukvdhP6KNNDGjoerdMZ2ICuiTE0xFSi/qWvtS7Ly2XoaagO6Y4iSskwrC1qauKb+aGA8HmZrlVxJvX/bFiz+/KHC+Psutqw5eqXqjN0aX9IxycVn/NryOXpeJwteph1pfxXb6q8g=,iv:0BJ2ziTFskxZJv0C6VaXx5sAQOxaYzIMmhePsklIAeI=,tag:rT29x6f50aDmc/Ger6kF1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      trustedCIDRs:
        - 10.69.0.0/16
  http2:
    onInvalidMessage: TerminateStream
  http3: {}
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WUVYR2JpR3NCRkwva0tY
        TUtVbmtaK280Z3M5Zkowd2c0Qmg0eU1hTnhJCjFaZ3NRSXdDby9vRm9rSzZQZ0VB
        bGZDekF5U052N3JnVHZ1ZU8zcms2cm8KLS0tICtXRlBJK2xreG9JR0t1WmlKWndw
        aUJJNmFWVmU0Slp2TWxFdnRwRlljK0UKXeOYKQ1b/2/lksYrA9MYSIcRW2DnmgTy
        4D+U3iBNkRwJiouxFLQhw9V58kUf5pGlyOwaoTWQU+37TI8pthFH4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T19:31:57Z"
  mac: ENC[AES256_GCM,data:YORy5aGPwRFWTFSulfn5J4crz5P1A0BK4QvukvdhP6KNNDGjoerdMZ2ICuiTE0xFSi/qWvtS7Ly2XoaagO6Y4iSskwrC1qauKb+aGA8HmZrlVxJvX/bFiz+/KHC+Psutqw5eqXqjN0aX9IxycVn/NryOXpeJwteph1pfxXb6q8g=,iv:0BJ2ziTFskxZJv0C6VaXx5sAQOxaYzIMmhePsklIAeI=,tag:rT29x6f50aDmc/Ger6kF1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: http
    - name: envoy-internal
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WUVYR2JpR3NCRkwva0tY
        TUtVbmtaK280Z3M5Zkowd2c0Qmg0eU1hTnhJCjFaZ3NRSXdDby9vRm9rSzZQZ0VB
        bGZDekF5U052N3JnVHZ1ZU8zcms2cm8KLS0tICtXRlBJK2xreG9JR0t1WmlKWndw
        aUJJNmFWVmU0Slp2TWxFdnRwRlljK0UKXeOYKQ1b/2/lksYrA9MYSIcRW2DnmgTy
        4D+U3iBNkRwJiouxFLQhw9V58kUf5pGlyOwaoTWQU+37TI8pthFH4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T19:31:57Z"
  mac: ENC[AES256_GCM,data:YORy5aGPwRFWTFSulfn5J4crz5P1A0BK4QvukvdhP6KNNDGjoerdMZ2ICuiTE0xFSi/qWvtS7Ly2XoaagO6Y4iSskwrC1qauKb+aGA8HmZrlVxJvX/bFiz+/KHC+Psutqw5eqXqjN0aX9IxycVn/NryOXpeJwteph1pfxXb6q8g=,iv:0BJ2ziTFskxZJv0C6VaXx5sAQOxaYzIMmhePsklIAeI=,tag:rT29x6f50aDmc/Ger6kF1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
