apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy
spec:
  logging:
    level:
      default: info
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        container:
          imageRepository: mirror.gcr.io/envoyproxy/envoy
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 1Gi
      envoyService:
        externalTrafficPolicy: Cluster
  shutdown:
    drainTimeout: 180s
  telemetry:
    metrics:
      prometheus:
        compression:
          type: Zstd
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VVNRTVphMnVhckNOOUJ1
        N3NucytGWFlqa3hsdWd2TzJmMmZqSklmODAwCi9oOGtaZ1B4c2pGR2QzUENPL3Uv
        c1BQTEV3TTM3UTNmNE9GeXpXSU1vRVkKLS0tIFordlRzeGJQNForajZuSFNIWnpV
        K1NFNUw2dHNJN0hkc3NCVldJUDZsMkEKyALQBRjNEeZSlE1/cqvpSVdAySEaWd5U
        1JhV/44BTU7GR0q6On+QOBLU5hoU/w/IfRaPxr7cIRg5UQAJ3OdRnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T14:12:22Z"
  mac: ENC[AES256_GCM,data:89WG+iknzTVbmJg6NH1XvMj1M2agsv/MtXipiFeWt4boN2y9Uieo8TLFo9Ma9ebvTFXwLfu9AMYNBeF6sSutJaretQwxD3fzAnP4VmmDK0gEWt+xul85PPNAFgLfNcBzScKs6sBmBEdU1C2V10/Vnxzd5aXTTOn9nFwUE55a22o=,iv:Ba4AxOb4I9jSC3qvlQY3k2Nhn7yL+uOW9+QKzNg+m7E=,tag:NhWpiVdhH/PEhxuFvsMKBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy
    namespace: network
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VVNRTVphMnVhckNOOUJ1
        N3NucytGWFlqa3hsdWd2TzJmMmZqSklmODAwCi9oOGtaZ1B4c2pGR2QzUENPL3Uv
        c1BQTEV3TTM3UTNmNE9GeXpXSU1vRVkKLS0tIFordlRzeGJQNForajZuSFNIWnpV
        K1NFNUw2dHNJN0hkc3NCVldJUDZsMkEKyALQBRjNEeZSlE1/cqvpSVdAySEaWd5U
        1JhV/44BTU7GR0q6On+QOBLU5hoU/w/IfRaPxr7cIRg5UQAJ3OdRnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T14:12:22Z"
  mac: ENC[AES256_GCM,data:89WG+iknzTVbmJg6NH1XvMj1M2agsv/MtXipiFeWt4boN2y9Uieo8TLFo9Ma9ebvTFXwLfu9AMYNBeF6sSutJaretQwxD3fzAnP4VmmDK0gEWt+xul85PPNAFgLfNcBzScKs6sBmBEdU1C2V10/Vnxzd5aXTTOn9nFwUE55a22o=,iv:Ba4AxOb4I9jSC3qvlQY3k2Nhn7yL+uOW9+QKzNg+m7E=,tag:NhWpiVdhH/PEhxuFvsMKBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-external
  annotations:
    external-dns.alpha.kubernetes.io/target: external.gitlab.be
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: external.gitlab.be
      lbipam.cilium.io/ips: 192.168.1.23
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: gitlab-be-production-tls
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VVNRTVphMnVhckNOOUJ1
        N3NucytGWFlqa3hsdWd2TzJmMmZqSklmODAwCi9oOGtaZ1B4c2pGR2QzUENPL3Uv
        c1BQTEV3TTM3UTNmNE9GeXpXSU1vRVkKLS0tIFordlRzeGJQNForajZuSFNIWnpV
        K1NFNUw2dHNJN0hkc3NCVldJUDZsMkEKyALQBRjNEeZSlE1/cqvpSVdAySEaWd5U
        1JhV/44BTU7GR0q6On+QOBLU5hoU/w/IfRaPxr7cIRg5UQAJ3OdRnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T14:12:22Z"
  mac: ENC[AES256_GCM,data:89WG+iknzTVbmJg6NH1XvMj1M2agsv/MtXipiFeWt4boN2y9Uieo8TLFo9Ma9ebvTFXwLfu9AMYNBeF6sSutJaretQwxD3fzAnP4VmmDK0gEWt+xul85PPNAFgLfNcBzScKs6sBmBEdU1C2V10/Vnxzd5aXTTOn9nFwUE55a22o=,iv:Ba4AxOb4I9jSC3qvlQY3k2Nhn7yL+uOW9+QKzNg+m7E=,tag:NhWpiVdhH/PEhxuFvsMKBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
spec:
  gatewayClassName: envoy
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: internal.gitlab.be
      lbipam.cilium.io/ips: 192.168.1.24
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: gitlab-be-production-tls
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VVNRTVphMnVhckNOOUJ1
        N3NucytGWFlqa3hsdWd2TzJmMmZqSklmODAwCi9oOGtaZ1B4c2pGR2QzUENPL3Uv
        c1BQTEV3TTM3UTNmNE9GeXpXSU1vRVkKLS0tIFordlRzeGJQNForajZuSFNIWnpV
        K1NFNUw2dHNJN0hkc3NCVldJUDZsMkEKyALQBRjNEeZSlE1/cqvpSVdAySEaWd5U
        1JhV/44BTU7GR0q6On+QOBLU5hoU/w/IfRaPxr7cIRg5UQAJ3OdRnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T14:12:22Z"
  mac: ENC[AES256_GCM,data:89WG+iknzTVbmJg6NH1XvMj1M2agsv/MtXipiFeWt4boN2y9Uieo8TLFo9Ma9ebvTFXwLfu9AMYNBeF6sSutJaretQwxD3fzAnP4VmmDK0gEWt+xul85PPNAFgLfNcBzScKs6sBmBEdU1C2V10/Vnxzd5aXTTOn9nFwUE55a22o=,iv:Ba4AxOb4I9jSC3qvlQY3k2Nhn7yL+uOW9+QKzNg+m7E=,tag:NhWpiVdhH/PEhxuFvsMKBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: envoy
spec:
  compressor:
    - type: Zstd
      zstd: {}
    - type: Brotli
      brotli: {}
    - type: Gzip
      gzip: {}
  retry:
    numRetries: 2
    retryOn:
      triggers:
        - reset
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  timeout:
    http:
      requestTimeout: 0s
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VVNRTVphMnVhckNOOUJ1
        N3NucytGWFlqa3hsdWd2TzJmMmZqSklmODAwCi9oOGtaZ1B4c2pGR2QzUENPL3Uv
        c1BQTEV3TTM3UTNmNE9GeXpXSU1vRVkKLS0tIFordlRzeGJQNForajZuSFNIWnpV
        K1NFNUw2dHNJN0hkc3NCVldJUDZsMkEKyALQBRjNEeZSlE1/cqvpSVdAySEaWd5U
        1JhV/44BTU7GR0q6On+QOBLU5hoU/w/IfRaPxr7cIRg5UQAJ3OdRnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T14:12:22Z"
  mac: ENC[AES256_GCM,data:89WG+iknzTVbmJg6NH1XvMj1M2agsv/MtXipiFeWt4boN2y9Uieo8TLFo9Ma9ebvTFXwLfu9AMYNBeF6sSutJaretQwxD3fzAnP4VmmDK0gEWt+xul85PPNAFgLfNcBzScKs6sBmBEdU1C2V10/Vnxzd5aXTTOn9nFwUE55a22o=,iv:Ba4AxOb4I9jSC3qvlQY3k2Nhn7yL+uOW9+QKzNg+m7E=,tag:NhWpiVdhH/PEhxuFvsMKBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: envoy
spec:
  clientIPDetection:
    xForwardedFor:
      trustedCIDRs:
        - 10.69.0.0/16
  http2:
    onInvalidMessage: TerminateStream
  http3: {}
  targetSelectors:
    - group: gateway.networking.k8s.io
      kind: Gateway
  tcpKeepalive: {}
  tls:
    minVersion: "1.2"
    alpnProtocols:
      - h2
      - http/1.1
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VVNRTVphMnVhckNOOUJ1
        N3NucytGWFlqa3hsdWd2TzJmMmZqSklmODAwCi9oOGtaZ1B4c2pGR2QzUENPL3Uv
        c1BQTEV3TTM3UTNmNE9GeXpXSU1vRVkKLS0tIFordlRzeGJQNForajZuSFNIWnpV
        K1NFNUw2dHNJN0hkc3NCVldJUDZsMkEKyALQBRjNEeZSlE1/cqvpSVdAySEaWd5U
        1JhV/44BTU7GR0q6On+QOBLU5hoU/w/IfRaPxr7cIRg5UQAJ3OdRnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T14:12:22Z"
  mac: ENC[AES256_GCM,data:89WG+iknzTVbmJg6NH1XvMj1M2agsv/MtXipiFeWt4boN2y9Uieo8TLFo9Ma9ebvTFXwLfu9AMYNBeF6sSutJaretQwxD3fzAnP4VmmDK0gEWt+xul85PPNAFgLfNcBzScKs6sBmBEdU1C2V10/Vnxzd5aXTTOn9nFwUE55a22o=,iv:Ba4AxOb4I9jSC3qvlQY3k2Nhn7yL+uOW9+QKzNg+m7E=,tag:NhWpiVdhH/PEhxuFvsMKBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
  annotations:
    external-dns.alpha.kubernetes.io/controller: none
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: http
    - name: envoy-internal
      namespace: network
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VVNRTVphMnVhckNOOUJ1
        N3NucytGWFlqa3hsdWd2TzJmMmZqSklmODAwCi9oOGtaZ1B4c2pGR2QzUENPL3Uv
        c1BQTEV3TTM3UTNmNE9GeXpXSU1vRVkKLS0tIFordlRzeGJQNForajZuSFNIWnpV
        K1NFNUw2dHNJN0hkc3NCVldJUDZsMkEKyALQBRjNEeZSlE1/cqvpSVdAySEaWd5U
        1JhV/44BTU7GR0q6On+QOBLU5hoU/w/IfRaPxr7cIRg5UQAJ3OdRnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T14:12:22Z"
  mac: ENC[AES256_GCM,data:89WG+iknzTVbmJg6NH1XvMj1M2agsv/MtXipiFeWt4boN2y9Uieo8TLFo9Ma9ebvTFXwLfu9AMYNBeF6sSutJaretQwxD3fzAnP4VmmDK0gEWt+xul85PPNAFgLfNcBzScKs6sBmBEdU1C2V10/Vnxzd5aXTTOn9nFwUE55a22o=,iv:Ba4AxOb4I9jSC3qvlQY3k2Nhn7yL+uOW9+QKzNg+m7E=,tag:NhWpiVdhH/PEhxuFvsMKBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
