apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildagent
  namespace: home
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: buildagent
  template:
    metadata:
      labels:
        app: buildagent
    spec:
      serviceAccountName: buildagent
      securityContext:
        fsGroup: 1000
      containers:
        - name: buildagent
          image: neichmann/buildagent:arm64-20260902095519
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
          env:
            - name: AZP_URL
              value: https://dev.azure.com/Cegeka-Engineering-Studio
            - name: AZP_POOL
              value: ImmersiveRoom-Jetson-Staging-Agents
            - name: AZP_AGENT_NAME
              value: k8s-agent-1
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildagent-token
                  key: AZP_TOKEN
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          volumeMounts:
            - name: agent-data
              mountPath: /home/agentuser/agent
        - name: dind
          image: docker:27-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          args:
            - --host=tcp://0.0.0.0:2375
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 4Gi
          volumeMounts:
            - name: docker-lib
              mountPath: /var/lib/docker
      volumes:
        - name: agent-data
          persistentVolumeClaim:
            claimName: buildagent-data
        - name: docker-lib
          emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildagent-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildagent
  namespace: home
---
apiVersion: v1
kind: Service
metadata:
  name: buildagent
  namespace: home
spec:
  selector:
    app: buildagent
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
