apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildagent
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildagent
  template:
    metadata:
      labels:
        app: buildagent
    spec:
      serviceAccountName: buildagent
      containers:
        - name: buildagent
          image: neichmann/buildagent:arm64
          imagePullPolicy: Always
          env:
            - name: AZP_URL
              value: https://dev.azure.com/Cegeka-Engineering-Studio
            - name: AZP_POOL
              value: ImmersiveRoom-Jetson-Staging-Agents
            - name: AZP_AGENT_NAME
              value: k8s-agent-1
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: buildagent-token
                  key: AZP_TOKEN
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          volumeMounts:
            - name: docker
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildagent
  namespace: home
---
apiVersion: v1
kind: Service
metadata:
  name: buildagent
  namespace: home
spec:
  selector:
    app: buildagent
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
