apiVersion: v1
kind: Secret
metadata:
  name: buildagent-token
  namespace: home
type: Opaque
stringData:
  AZP_TOKEN: ENC[AES256_GCM,data:1HWn0mq+fHVwjdLrs8VKwbY60Ed3LG7MwzpILnjoH1iG43cR7Uwt1doIydd8EYUqrb5OYXFCOmAFq6Jv88vhbmn8Yg71kouxAiXrADARnu5c1kUg,iv:GnXgg36mV4t/WxoBh0uvhjb37yY/i7Yy+Vc8nfdrOrM=,tag:uG1ND40Z+vrFfkYl9MgYaQ==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeDk2Q3F6WDVzZUJ2UjZN
        V1B6cE4xY1A2WjBwZVpnYkhTQys3bytya0RnCjJKN3ZpNTJJb3FXTzhvd1JBRk1P
        Um52U3phU2RURm16VjBoUGNoU2tVUUEKLS0tIGtJcW1yaEdkWDBiQVdPWHhVSnJx
        ZG4rVGdQK0JvS2FNZHZJbEs4ZjFPSjAKbIjiJO7+pZ+vJaNgR3PPioidheRTltj1
        F5gOnWGb5gKP95a/J+wxJWowZHYnpyAYmveX56gMb/QPN5mvALAMIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-01T14:40:31Z"
  mac: ENC[AES256_GCM,data:w3tF6iBi6ITWiTVi9geJDbm6ijn4O//yKtxZdqAWVyhGe0PQQCHVcE8Keo8lyX3UTOfMgtCldJU5xl5sOu4tKDVwARMhOfLvvxFgLUlHO1r5U1tzlVx3NcXEW6nL4WHjgUusSCFvwHeAQAVPQenOygR2jYJ1NzwJQCSJEnDHL0E=,iv:Z1t6NdkOYZWx8fkaNXIYWxJf4f7SV/gLUGEpLVY9K2A=,tag:BsLWJ++QynMCE+KA1u2zAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
