apiVersion: v1
kind: Secret
metadata:
  name: buildagent-token
  namespace: home
type: Opaque
stringData:
  AZP_TOKEN: ENC[AES256_GCM,data:1NaiLwbNuBIX4fVF/o7sVrnDPpp31XKFSM0m1etSnH6qZrroND0wn1f21UyhQaBJvTHxmnDkz/5jIdpKOCzZ16pgLRCgMNLejpZ2w5iMZL5oto/P,iv:w76XmIJTCTWG6GaIAS4VdSUsRw92hB/BgKcQky47/ZQ=,tag:KOmtBxM33o4r7qxcCMxWmw==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOHpGaVR1bnZnbnRkY0xP
        RjZMN2hEK1dkYkFJZUNwRlE4cytDdG5sTEU4CkZzUkR4UE1EZnUzcFM2NGF0azNs
        anRzeElxVWNxYittS21rTUtXRk9xc1UKLS0tIGM4WkZPVGJhSVpUenB3clA5WVVZ
        NTJvQ1ZkVWVzTDhod0dBVDlTLzJvM00K4IWh43KSEB70Ou3bIw9xRSCPQqaFSY+1
        11md+Sq51SazXd/S/f+BtdOP6HeAOBBEqIeQNCv9dXl9uzZntLVtpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-01T15:32:44Z"
  mac: ENC[AES256_GCM,data:XCwDQAgHgImGUUltYKsvIWUitl6C4dlbnLbE8SCuyb99i0izGHhWumXdeav7cM+tIAIsGaECRzpR9YOqHyNxi87aenNji2MdpYzxvlUpVjF9Fs5ynmzNW1rIEZrhko9FyTYdmMXtTQNaoFzgXT5wtWJSfrM48ACswjqivUhcb5I=,iv:/uRXudlPKeOJYbXskryy9OJgnZzEwp+bw0VyszW6bkI=,tag:et0LrIpZ1ZjcqJzvcQLhvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
