apiVersion: v1
kind: Secret
metadata:
  name: buildagent-token
  namespace: home
type: Opaque
stringData:
  AZP_TOKEN: ENC[AES256_GCM,data:XhnG3UDeF9v/yUiMi3g0P05jW5u4M4njE1vixIGBXqxmnUfRdxudK7bH0IOGDU6HikCf7MJLb5fI+r3oxIko+YrBHNvIquSm57Ub+l3ENhP5HY5Q,iv:upG05sLTQxMuVBtI6p+lzFnfLRltF5UJlDD/2q0hqjI=,tag:fQg09sG7qTWeqN0hwJerNg==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkYUUrM1RYcktEdE5DcEF6
        UHljckZPbUsxcWhyY2g5VUh2WHEzaiszalJZCjlSeUxUNzNUdmxkMlB2Tks1M1lF
        NW50dUwxdUNMeTV3VFJ1NnRTSE9mTVkKLS0tIE81TlZZVkxDZGQxNkZmTG9nSVFH
        ZVhxYjBRUTFuN0hIUjl0R3JacTVyVkkKV45psepObSmLuKiZx2g7V+Y1YCeciG7X
        ST1hCKpKk8VMVc9c90aluZIUejJwGDHAJoB8RJse7oKiWG2Rx7ZpHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-01T15:19:24Z"
  mac: ENC[AES256_GCM,data:eNq/2p9AEbZNEnF1tSavlFD1y6d97ldJ9oVo1OwS5ipipWnnfnno87Yg6vHb4OXRicLOPTpf2FuNrqq3aUHhUZSWM8Hd7+BROpGKh0r6UUcDNbHSAuijgSvvIxqD3Mb92fnCCFd60op03HoBtM9xOMPXb+EzXCHmP/JxS/Xp9uA=,iv:/yABbZq5Yme+Gd5tmBV+tAJ/ZL/IgL8q71/NN6gjw/o=,tag:1js2cLjPXMpmBsA0RoZ1VQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
