apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTLSPolicy
metadata:
  name: unifi
  namespace: home
spec:
  targetRef:
    group: ""
    kind: Service
    name: unifi-service
  tls:
    insecureSkipVerify: true
