route:
  app:
    hostnames:
      - echo.gitlab.be
    parentRefs:
      - name: envoy-external
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 8080
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMnFtYTNOS1hNWDZOanJy
        UWdyWlppaEoyTE9tSGkzVGphTXpUUDNBd0FBCmZwWEN1NTlNdDd0a2FuUU5iby9I
        RnY2cWRCYVpPSzRVN2szSTJvVVZPZ2MKLS0tIGxrK25LdHVJc2N4a0ZPZTlEWTlB
        bmd0VlpncE5hMDlYNFlYLzh4bWZLNDQKwLD8bixr10ZwVLMtGhmABvYh+TywyWfH
        8PZXGtx89CUDbIqY0Y2REJLwFT0+eJOyzvWoPVVcFoaD2WB7SUyz3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T08:22:22Z"
  mac: ENC[AES256_GCM,data:Sp2Y69leyxBG0Z8rPBd8lJHj8/xeB5RSHQ4dhhk7yb5i9cD4K3/9Nr7jx/cmLFIN1TzX+m3izL7EZrQPEceeMPaMSWs76QkEA0aVgxwX459+GExYiHH1AB3POkhWhxpmlhwiyrcW6tOj3zcb6mYykgOJI4B5BiFKw++xLPvW1cE=,iv:49msdjZ1gzD+7GPPeDpn9J4CEnRkJ/FE0l6MIiT8wA0=,tag:UxJpEdRCkzkUGfrvqd2jmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
