fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - gitlab.be
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUG96K0VXRFdadmlKaTJy
        UjZER1ZDTE5FU3FzemV6Mlo2ZE9lZmptQTN3CjlPVkZrYnR1d05vNXJUWHA1b094
        T2RNRTFSRm9QUTJSRUcxVlJIek50alkKLS0tIERETVZBc21NSjVRVG9jWEVjK3I3
        Z1VvcE94NHpCQmZFODhhZFl3YTBBbDAKiiVs9qcSMDORQuEfe72UzZWO744+Us4T
        8bxdB5W7nxwdrApVnbovlKGby1UJiiReomuIrX+ZGDJ3Q/8GRKDKHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T21:19:36Z"
  mac: ENC[AES256_GCM,data:hAQBFWh4mU74Gmxqq0fEIieH8hlvfHm3H04tBDO533hkTOdQ6Odbw1BTcTI06RkkL+KRWWLz7121YbiYv5sv7IryHO93V2oS0F6GW6jiqp4YXkeWbKireGB+HGdv/ZuGsBVGkd3fAZfxMoqqdt75l/qfsx1rNu1RMx8OXAOZU30=,iv:YZbI0wqOAbAXvgAqNUoMqhojZcdP9C0nid+L0LQty6w=,tag:JlscXHPLFB7nhWJ2Kp1ssg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
