fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - gitlab.be
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTlQvRjNTOVc3VmV3Qyty
        SmhBR2VROWhLZ0tBdGlZcENCYmJ4R1ZkMUVZCmdPR0dZOXV2V1YvREpqRlVzakdT
        TjYvVzA5aWVKMUxQbE03YnZtU1J3bkUKLS0tIEE4TnBEN01lSUtvYzRDRWdZRU1p
        VnZxTEF6d2VRVVZaSFFGNmJYMzRVdDgKHQqUKchANqWhe+6jsE/W1+HiTvz+5lY1
        NsfyaGvg1DY0TxdYFUF4AN/iSMvMwyjyYt34D77rw6BbLUCsPWCW5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T20:00:42Z"
  mac: ENC[AES256_GCM,data:Bjoo+8UmguVt/eamTK9AVBwiArTRRuZDg1whXFAucVaC8aVFv9UGu6kYbwVbi1lZ/kbcihyowz4GteZJBIHsd7sjji9G9rHa3RU1UwvVRuYQEBeOdcvSqUDbEGycb2Xk1fSbOGyYFk6zcze02/8gAGTkqPrVR9qUvarqCNcmXQg=,iv:yhyIxe8qRYKvo+cAphcmxN9VJSai8Zx1Vbvwepjh+uM=,tag:9vetT2pzo7gD+n7BJ8T7Ng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
