fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - gitlab.be
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZWgydXozdlVwKzhPZUlG
        cDhrNFR1QWpvY2Jzb25rTjVpK3RUeTUvaVR3CmJNSGt1OVZNdU0vM3hVTWZFVzhI
        YmpMSWV5NlNWNGcvWGJ6TUIweEVhazgKLS0tIDlmMFRhTDk1aEF3TTFhK0FwMVZR
        T3VKa1VyL3hSN20vQWc3M0xjNkorQXcKZHJX9sqfHLEChkjOsmgHV2m1FhPrtv3L
        9Td0PnRoBskPhswDPh7GB/cfmEokkrJbcu/Onf/FijkZX9UOPN+v6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T21:51:10Z"
  mac: ENC[AES256_GCM,data:WYBhwKkhrYau27oIiVgAltrmYR5qywUfTSCVj97n9gNia2frZxamRXtbjf/t7qeeRi3MXDN5yAeZk683neHw5L612fn8oe3dNrLsdvRYKdxB9V36gnSUXsTOmoZ98YVpGzONvu0U8j4sXJmgI46ka2wRHllH65dV67foTNPNM+8=,iv:vwMGsmkIRUsqatY6zhANncz0TfAjELcM3qF2QzbxpVg=,tag:7ChdJgIRtrm/uyn8Ce8S/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
