apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:/m6P,iv:6ENteKj2VWvvVOPHyL+YOi1KEmYcjsB3EZcvX8pEu3o=,tag:TG3YasSRmHia6UGQlZZkXw==,type:str]
  url: ENC[AES256_GCM,data:oAxbTY1xQOhiCUBmUaohr9u14AmAIVhoNNkT1PMnhegKCSY7D/k15WgDn0E5qZI=,iv:V+ir3h/x7GERboc4ESrcTvNzSY5A9wTh5Fnytvh/u10=,tag:PVj2zR5Le//ZbXgJ7M9EVw==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWUE2bnEycWxpMldiMEdQ
        Uy9CMmFkbnkrbXIxeFl2MFZ6aEJONy9rTUFFClBraWtmc0FaS3d5TzBFQ0tyK01D
        ZlVHYnAzSjNjNSs3eXVON3Bubmo5T2MKLS0tIFpiOVNpdjc1MGhkaVRvOVBjcUVl
        OUI0SmpFUTYxTHlFSjdCdWlGMjZOQ2sKkXtn5mptz/G3jNbXN+8xBDayUwhuEr9o
        kk90kW0jbo/bkvPRH2kqwwEYzFwyqHFgm8g65ouwROo4jF45hUH12Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T07:29:51Z"
  mac: ENC[AES256_GCM,data:962mPeeBGsRe0aw7SDMhW2RpEkOn0MgyYObu/aBKjL5PkzFg1SAg96K6wMs+SF6qubZsGzI4TQua3kK0xGyL+V1cNLTmmQGbmQ/KGljFhaNeFRi+TqSdzUt4RNsMr5LdYxc92AgUBd9mGUKMjgoVIRg/+mlbqNZlNPAH7/sk2s4=,iv:vSmua+4Kt8iHFeCciOkO9LBL3O59k4kxtqupZwI7/uU=,tag:REjLqH82LVkmUyAzGxX9rw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
