apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:rMJ5,iv:g4Y0+NUPDe89a/fQWDk9ja/f3BSrygOaeIdJKSKUgSk=,tag:u+SWcK77JeNVec0C7MwEIg==,type:str]
  url: ENC[AES256_GCM,data:kF3RsQ1zA1h+hdYw2ZQHt4wJUTIMaLGNXi627FOBUfXLJysMXCvZFyE+6D/01ek=,iv:C5bVLrPLPU4xhCWm6SX4HeiEzu/5g4nicHMAdwqsJxg=,tag:d1r80umTtm5pbPtJBPwQ+Q==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT21xNWIzdHRXRjkyZ1Br
        N01veGV4VkJFRHh4SDdWblFaTnQ5ODFQbHdZCkZpL0U5Yi9HZXdlVll6VlpwMVR2
        aUF0K0I3ZnB5RTNzOVRjbmJ5VHhKUmcKLS0tIE5DY01MZ2xWeDJ3VmYycmpvenk0
        M0xXUURJRnJjZjJVTUFlVHpjYXJ2ckUKKAsGVy2F4pn6VkT5tqo+M+YfK2FCXPwC
        mGa7MmaY6CdLMIVAsMSuF0Zyvgv5v+pzZzRJsT8aW6ORHm9tdbNGTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T17:03:30Z"
  mac: ENC[AES256_GCM,data:8vfyfHNRHa49ipDQmceFLuIbr1ki523NamqtQHolCCmfm8KvctMkHCseHjXopGDzmEPng6/g5qbEku/kiVcQGF0yGxEE61QU4YWcPOJ0eKTEhlcvqK2uR5FA+lP1OJMjJUwX1U3HCrsTmFRXDs1lnWg19yc+deXNMkjH821fkJw=,iv:G+vLz2u6m/fDhM6iqPFPb3MmvI+mvA9nVHRI0A56ENA=,tag:iPH9qypE7dWZR3qakeOnZA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
