apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:t68A,iv:TJBxJjYEceUKOXSK6shzffLlksuwk2MD/8cJ2L09vKA=,tag:7zpziT9qbGlRvPVXcMa6Ug==,type:str]
  url: ENC[AES256_GCM,data:xAuBHWiVITqbn514Qy5o3tPiTXhWbZYVz4nZR1G6XOLssOdXrjRCyB5ZkSPUNFA=,iv:iWY27FsGFeB8yY+E5w5FsGAEE4WELCxkwDv3KXVWwxc=,tag:4KSHORMWSVg18z9XjQsJLg==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMDlNRG5aOHYwWG90b2pP
        ZFo4VmMvWHVZK1BUWmRVQ3AvQ2V1R2tZYUFFCkd4QVZEWXVIU0srU2J0WlRVdWRH
        dlFFV1BpdllTRytUM0luUGlPNVFHYXcKLS0tIGx3L001TTVsRFJKVEVqcjhhV2xS
        aTZtdzZwMU84TEc2bU42cGtwMUptc00KuC3BdL+3uHTMHWlgR9D3Ejr8qeLHQqg5
        J+12NDuMhC1nvx43kAsDqBLbuE3I5P0nz9b4lkUr40KncWBbYF58rA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-01T15:25:18Z"
  mac: ENC[AES256_GCM,data:7f2I4QesX8gHH2YUS5x0HAoXSv4tKhSPg8d8NkWhn3uFDCKtEXsB69fk+Da9uKmBunHNGIBStcWOpTbSwCGNga26sivEir20YxkDF0Ngnsux7iQmaWEfP70qQRTRlSBDzOTjbma0UJ1nXXFkRKl9q0+9gKSJk5+RAgeWrernqnA=,iv:c30rCtcqcdJ8qz4Rz1nhSzTsLFW08oujjk4dxfDxhkU=,tag:whIwDPgVTbM5GPzuZyfIsA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
