apiVersion: v1
kind: Secret
metadata:
  name: whisper-db-secret
  namespace: milo
type: Opaque
stringData:
  postgres-user: ENC[AES256_GCM,data:a65uvNyxpREt794=,iv:uTuneQafi8/VOiXT6mSzXfWx9YIpc3EBT4KoXaz+fPo=,tag:8DsZxwrVtQDs5Wi5oyTJcg==,type:str]
  postgres-password: ENC[AES256_GCM,data:IS8AO7CVn+j+WsFSDU/p6rKTMI/jLqiCSg==,iv:5wxLLcY+qrKZwYNwuHdPENKk0HsoqIVl5r4v2RIKYuc=,tag:4yWlKZFpTkAY9MXiJvFWGA==,type:str]
  postgres-db: ENC[AES256_GCM,data:WU5L4qw7d3chVIUzYw==,iv:hvVfYA9TbsNmAknyYapN/Vr2kx442F5vsv1zsRnEcMA=,tag:3eKgJcjj8BK6++56GzhrBg==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTHVrdnVsUmlQUVcyMHM1
        Szc2VUpJSUw0S2ZFYlgzRGVWTk5FSEpiRzNjCjZBRElYYlNQS2VBT2JoYTdISU9R
        dDBkS0FkSFdwVmhIa1NOYTNwcmw1c0EKLS0tIExhcGdKNFJQSzBjWWJYYmJpR1ZV
        UHRxQWIrbEZuNEQ4K0MzTDZMdWUrK28K2UrRt7VfBexyCkdzph4SbYyoGdbCVUON
        93GxKAyH6sP8oUzInRSHOfG/zrScZkY/aZBovDdYF7a6IYd4jH25SA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-02T12:44:19Z"
  mac: ENC[AES256_GCM,data:a9iz5eFSHcRqZbjUW2WfwLZ7O/oaXW/jufbd9xMVb6yJYFvqAlP1bWx0M6pCKplGHnIu5/i1PjvjFZ8lfH3b5KByly2MYVxyBl4pb/jRcTd0f5WbXqjKl5pwGpWisaxykm0KmpNxnE9GXzpabickb6tREMB92BepdAHCCY6cHQ0=,iv:VbXAlwgY811zj0rExIjH/KFfK4uZeeHM7Npc8EnEPy0=,tag:kX5OZacpo/o9SqZKK6uTow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
