apiVersion: v1
kind: Secret
metadata:
  name: whisper-db-secret
  namespace: milo
type: Opaque
stringData:
  postgres-user: ENC[AES256_GCM,data:C+jdaCa9ezp5EOk=,iv:aeXCriioDBPVNnQAfDCj/iqTqkVSGkrDVx/Ib3NFr28=,tag:Pgv9njNjrVLLZC6LzBjolA==,type:str]
  postgres-password: ENC[AES256_GCM,data:9iIW+K49LiQpdLK2tyGwhqr0AxxPzmv7DA==,iv:pmnZEQtyivrTDttW68hyn1DnsiWyThoTbAVPGWxMTBo=,tag:rc+ErfalASTlVTgyFqY58w==,type:str]
  postgres-db: ENC[AES256_GCM,data:3lcN7UszaOfPVs1jcA==,iv:5RoPt2WUz18c0DiDiU8MZOXF65ny+hlXL97eI9sxFxQ=,tag:vS6Y6nq63KsljaSWTMQY0w==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRkxieTlQblp0eldjbkRY
        S3IxS1lPM3JZc2ZsVTUraE0vVTlLUmM2UEQ0CjlVREk5Ri9FVU5STkN3YUhYUDBH
        TEZlWmlNQ1ZpNmZYUi9qakpRRmV5bDgKLS0tIFI3ZlVwazdBNjAxYi9YQ0JRNnVB
        ZjBHZ1JTWW5CcnlyWjRPelVDQnhGUjAKzqKMNPXbQA75XUr0jV/zLIfi2KKAj9Gf
        5e/IN7kVnnRP5edNSHuif9BvOnVUVX4c+nP2Dz2s2DyXWnrZgH73yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-02T11:16:04Z"
  mac: ENC[AES256_GCM,data:UhVcHrtqHK61Ja43ELZuz6Kx2Evn47WQ22XVLKCxLOnpie7VxdIecKNwfNYN1kcardkQR2uX0vBADH8X1PxoagAboQYmr/3HVf0D9mqUpS0P8zME9lYrKE+vnwQpV981xXdsUUzrRqumCGBUPtVACpEkQZj3G9fsj5kIf1rMBIU=,iv:qnEL2KfGDELFcLgBKouWqehpTUr+DIyk+TRGndIilLM=,tag:9e6RUb1gNzcAjUDV4YGd0A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
