apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - gitlab.be
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUUZvOHB3UEpKelFITHgz
        dURwRlczZlZzYjNGNG9tYklCWDZhL3BpOWs0Cjhjc0ljTGx6eG54VDI1YVlxOXJY
        eGtxY1RxQnp2aHVTeU41Z0hDVWlzWnMKLS0tIC9xN3VDdjNwWExVTjd4c2ovNUFD
        ZCt2cVMxRUVsWUllbXQrdFBIaUh1WkUKicAB66XiGWBVQPJ+3yOPPGB5iFWiAUkd
        hENZQ5mnY0FBx7dPTdSP6UlYoAgjZFAEO/o6b2r4FFJMAdfFFi7H4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T14:12:22Z"
  mac: ENC[AES256_GCM,data:5+pkYiwOADritR1Uz6KOtqaLEN5cf+afSmgkK7b2CopFvz8nhPdse3ynx1joL83+M44ijYrueOKiZVn5h+EbKdvrxNT2VbeXp4b5yIyjBpVl36zZFNF23oHyGQ7URU+wq8SGsWVaUotalfuI1h7AZrjXFWoDWSZDaNvNnspLnPo=,iv:RGrPcSx5i4yXLarQHk/783lbQ/s3GCAOW51p9tZOiQE=,tag:kn1RtDZzs0MsqxPMWpF+HQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
