apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - gitlab.be
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTzFHaHp4OVQvVTJKa2py
        b0M5aVY2c3BhUEc0L2FTRWlOZkNCSVBoaFQ0CmIrZEhlZCs0OGYwWk1kQ041QkFH
        TVptN3gzYnpSQWE4U2t6VzJrWkttRDQKLS0tIDVxV08yM1YxTVlsUFE0enBocEIr
        YTJJdWpTVEsrM1Fxc05KVG83Yi9MdTQKXzxD1A0iQOvkGs0pgUFC6dQswp/KvRdT
        3WeQ8qqVz6hN0wTEEjeNaLj1yebWGs9uQGUyOV+Sp30gIVG/1anljw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T14:44:19Z"
  mac: ENC[AES256_GCM,data:Aq3TcdDthTofQbAqJz3AVKJRZsmMZtQktHVk5ThrY2aP2GHUFi1jqIJlnKY9De19DEJF66RalkyKmfQF9qieOAfUVIMjGJudZvrJooh/LwfUk97B1nyDTiZukVtjTUw+4LCLdmwRZgbjMKMtPNZnMpWj/2dnu/bNJ+my04yYR64=,iv:dR8hbNovz+5DlrvHpUWZz8dJ0jDoXC1/zBM3MpQQUXo=,tag:Yteo+OnQwMqLZ+Nayc8Ksw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
