apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - gitlab.be
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UTlZU3Bnd09uRW9vUEtR
        eWpMajB5aTZ3b0lGT21MYnRyS2U5ejFBVjA4Ckk5bldQbE1Jb2xQR0s3c1FNb0Ur
        YUFHc1pQQUVLRXJDVW9paHdCSlJtVjgKLS0tIEV0T3BGYVFDZ21DQ216empEcHMy
        dXdqc0NRU3JobTIwQXFzcXRlZTE4MmcKXaNRNOdyPQfMc3H61tVKB9ZNtWI/+Lf5
        PNaBsAqZpwV8At5allhX6kcsubyKJHMyWvlpBridmouy/6am2bvHGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T06:52:37Z"
  mac: ENC[AES256_GCM,data:v3nc3tL32h0NM/4qCrLktUY5hqBQi9yYrPndI77XIRXw89ThkZNa+jd2/aWaA9NxZ7BdTZk99A+wxMDHhiEsDlro57p8HilYnbn1o6vuwNf7WWaEr6gPssJith0y6F+lb126zroiQF5eskyUZqmnT3Xo+UjqvIvYGiZZc1RQL1Q=,iv:b17iMrwo+1yWEvmy23fKYrdAgefinrnBVDeGGYQOvYc=,tag:FiEXhdJFl6g9EZNHhhks0Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
