apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:gRtTWP2/sBLTjlkM/IWqGbRSAvDf1XApjtUsnageI0wqiElhZ50JSg==,iv:/d+eNMnxkDZ/aV4947CD5B8uugJdcriCnOouEmErElA=,tag:JXH4aIQeTK+ubKm/u2RB0Q==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d0dLaldUbG16WmF5Y2NY
        U3ZNQ0F6MmhvMUs5UnZUQXpMQjNGaUx6M0FjCjlhaGhzZFljTnh3bmtUelpIVUdL
        NVN2ZGE3c21IWkZNc1kvaHA5czRVQkEKLS0tIGlYdllZNStCeXpmTjc0alB6Z3Vz
        Z1FueTdOLzJWeDF0b3VPOEoxeXVZNWsKD5/3jLxVbE4VWX0w7s1CzEFLqqyxixiE
        r7/xD2Nhe+ijKyv2CSM1UR/siXZnS/KbWqif7EHaiMxpxa/KsOc9Nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T17:48:37Z"
  mac: ENC[AES256_GCM,data:0zR3EIn1JhLq+FJxwtAzxVyNQV6ilCqWsgxMKrPUgNNsPwOq/04HxbGh8WjgN12r4U730oAMVC/sHHzblB7cRbGfihPWCy+WGJNq6Qv9k80VnKWFCnx9JKcU2PSSCRsz2Jx8THfluA6/C/9QRt4MNsqFPV5WjRWg//fPKhSQNOI=,iv:BTHCbo2bHotVoYhTGSvZNrsYf4ZvAClt9xgdOv1Klyc=,tag:/E1NHjuJVZ1QjP9mDJAqjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
