apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Ef/UgVnzONt5RuujA4uTIYlBdIwz6IIojTxWyt4+4afk6n5dHEK0+g==,iv:/mjD7w65yyqginlAPWH79RA3Gy8EzUn0z6TJiLTSZes=,tag:7PoMFwZwgcU/68Fq7tnfMg==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiK0ZLZVlVOW9vUU5Cd1JK
        OWQwbk4wRGFPMWNaaG1LazF2dnBvYmtjalU0ClpnUUdGRHM0UVhXRnpXUGVxQi96
        UUpjT2pFVTVGS3ZEL0F4YTh2RVpXaG8KLS0tIHJQOXJrNVpGWTRpM0UwMnpKTlZo
        eWFJMlZKa2xOcHRpOGZ3eloyL3UvS1kKlzyHYc0Vf1AgXuaqt31YlspbB/+3UcNR
        9j/i4B8Q0p5+zcwzZ9oKPS6F1mQxzmyZXMnvdnr4PRdm8iOvuzj4WA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T19:38:59Z"
  mac: ENC[AES256_GCM,data:mHVL3AyjlPifTPRXX9Bz6zHXCZG9Wf/OSGnFSP/MtxBzxadlqnZcCqiKXkk6htiGNXr3lh0PiwVroYab8Pm9XpuGOFiJhu/nlKy2oKL0KfbVSplJGieI6n5w/wxvKyIqApiU1BxgLkQP3yQtbvVkL13oY0eapm9TuKIJChDFTik=,iv:zywtM+6ZerKFFvY775e6AvVAgB4MG1g18KX1vyd7PvQ=,tag:oGX8kKrYtWAM/6+QgyBgOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
