apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:x8K3k4UVH9I1B+GU3oTH88aId2ng4qwJ+U2QMrgrPpV59iWpQEXfoQ==,iv:TbcECyMVSUlKuYUephcIYIWon2lFeZaYK7ADMd38x+k=,tag:e78ye1v6ovefUYzeeyMR6w==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UE5IVWZ6M2swdmZ3OGg0
        cmo2azhibXgvTmwreWtONzBreTRISTlkNDFVCnF4ZkFRSXd2dUNsOWViTnNtWGdj
        Tmcrek9kQUtXWksxWm84R29JZVU2WlEKLS0tIHUxa2gxeEEwOGN1OXNHVVFIK25T
        dVVSeFpzZWVyclgxZVZyRzRsQytSbUUKwLqbmWwk4ZhqObVMP9VxPdLgzNSmI1Fq
        LvvN/NkEv0IHWpHULIUj38F6XvJMUGRC9oVk8z1V2Ey6q8TtFeoNYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T20:51:28Z"
  mac: ENC[AES256_GCM,data:E7ndGC+9uhXrgzkrt2Ie92Oed6a5XX0Cs8ihE+XVtBQn1X65aefTZRqTbp+vLC9ozb9cXRhC2Ap2A9bIQqxOriB6QsMnjZziA2Cc6qwAnqVIRtVB7KPmb9NyO87LLZ9BmZAXliHKM+cmXcdaSLw0q0MzceAi5QHNsBD+/u5E4wU=,iv:7nBr+YnJUDr7bmZhZ7W3i07ExR/W/Fi9kljxp4nmoig=,tag:863BZG054cd/po1dWMkr9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
