fullnameOverride: argocd
configs:
  secret:
    argocdServerAdminPassword: $2a$10$pLQyvYhQqYnVcFoZgdNFtO/iB8i1mi3j0ajcPm44ArqEJsBXRWun6%
    argocdServerAdminPasswordMtime: 2026-03-08T16:19:36
    githubSecret: 7799272cf6020db47885bdf60218700b
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRldLNmNaWFcvU3dQb3JK
        dlN3eGhwYTJKZVoyNGdaTTBJUFhOM3d5NkNzClB1UmR2aGdTK3Z4NklTSXQrRjZN
        R2VjVGxMd3hwWWhwNHdmY1EzbmMzYm8KLS0tIDU3SkZMSHlLYm1qWXFjdFFRL0pF
        S2RPRGhjSnduL2pmWU5qUWFFUTQwRjAKW7InkO7Hzin3MseEH+lxwSROZbGxk50n
        JOblCqDGjmzxRma6b0xGISQ2T7rB0pijCMU8KZw3rqV29K+rxw2xZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T15:19:39Z"
  mac: ENC[AES256_GCM,data:Kb8Sh0UrLegmlPTwmY7l1REbOlTyXEQbJDyfYpWplvMQEaB/gIRThBjz4MxvZfadGeavXhxYApz+WE3IXJGn9UHDGyV5WJkaayUNEdBMIsF01H+cl5k1ZvyTgSwBCbZjHtsYQOjBY/eFR5HVcSkCRpKTd8jt7qZ5kKh32Jq9wdk=,iv:XwGjcXu0kjiwHcdMqi2jW4ThcK0jS4XAbJIvrAzbygM=,tag:HQh8+OEuoH4ASbPAR/fPig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
