# This file should be encrypted with SOPS after rendering
# The password is sourced from bootstrap-apps.yaml (which is not checked in)
env:
  DB_PASSWORD: PostgreSQL-HTk47jMn9Qp2vL8xK
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcE10REZTU2pESXpGaU5E
        ZkdJd05SejVxdXk3bkVGNG5heUoyZzBObkY4CjdPdXdTMjcrR0Z2QXh4YnJpQitM
        TmVOVi8vcnJwYTRCczNUZmlPb2NyamsKLS0tIGt4K2o1VGh5Sm4wSWdGOXpUbXE4
        Ujc2YVZ6VkNBdDV1MVQ1OHZ2dUZBS28KFf9k2OklVBXNOQ1Hq3sX77R6tRlK49j+
        2oTJeW5NZqlDgD/vH64mPnJFDXbugxBPf40EOVrkSUVTvWBlfc0frw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-01T14:52:30Z"
  mac: ENC[AES256_GCM,data:ID/nPhglH528DaVASCzuOsL87YiXjzH+1eHgD+DdLwar6HZjZfob2ZCq6dc8VBVRojbog8CjJhLkWkziFt9z/tACZIdWuy8L+SKNe/Ryo5UVDCoDMI06UvTrnXHljA8LVqut4BlXOjEXcAWtHPVFdorm77kKvWGq6IqylAEAEHU=,iv:5hduapxzJjn3i/1wuS8qiyQdyXhTuE3+I45n04lemjw=,tag:78pwvpJ81s7NstZzUbYxLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
