# This file should be encrypted with SOPS after rendering
# The password is sourced from bootstrap-apps.yaml (which is not checked in)
env:
  DB_PASSWORD: PostgreSQL-HTk47jMn9Qp2vL8xK
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SEwxUzhYUkw4dWM2NE5R
        ejJsM3ZqWk9xWVJiNHFwc2pCUFVDd3JEWWdJCkFUYjY0WDd3QnZLZnViWU82MTIx
        NHd3WEIrQkh5ZVhEbXhCRGd0S1hFYjgKLS0tIC8wNkw3MUtteTRYNUZTaS9ZbHNF
        ZTVSMkZrcUNXWmo0bmpaSmFNUXJOTTAKwK7jfhHyILLXVjXOER0M4XOC+5Et3bwR
        cTDNk+9o79xOe5o+rICQo7xPzTUzIlSj2nBi0x1R/lKvzKEAFqtkIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-10T19:52:29Z"
  mac: ENC[AES256_GCM,data:hoOSET6SV9uiOznpzoSCWH0a6Rq+LTLLH3uv2PkEGf3dVYSTaEC9pgkZGaMskmGw8HsQ7gRDa4hoQo6c/KiXhS2H5YDHaiGGtTLuhlkIg81dVAawgUECKv/PX//8DP+quP48PxsMCd+VVbBAWpf0CvBpjKwiqqsvvhbhCqm47B0=,iv:eFzm2yw7a0uFH8Ju4Or9JgyjXdkrJLEKaX/G9xKpiio=,tag:Fz3kS3Qq8XnepBRJ8fWiPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
