apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:I5GFimUWodYEBUN7/Hh6n2WLJ6itqxmQIzh/SrUqySAI2lQsFC0G/AGffH7PH6ffqo2+CCOXc/oP0KxLEpoklRteF2TanzTuWpux,iv:MbMOMIIKN/EmF/l6+azHY9GFLIVBQ/l/o434aomff9I=,tag:3tLUrbmRZIhlHA9wCJbHZQ==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZmJxcitxOWMrUHJJa1hM
        bU5GM1RLUWlVVXZpS0lwVk1rN05Ec3pMSDBJCllNOXp2WFRBNjNhSW1xNnpYWVpm
        NUlRTnVvaWlHQ2daeVYvVUJ3Q3EyZjgKLS0tIEZWR1dxYVFUKzhvbkQxRkJ5enUy
        c3dLRVdFampEZU9iazV3MG5rSnJiWVEKQWi+28ZFC9YnMqRFe/TbCyPrE5667Bry
        my3QJN1Y2Qdkr4E4czIpjCwIluQJT+GPix/YXwnls9xL1v3o/C6Pog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T20:00:42Z"
  mac: ENC[AES256_GCM,data:EwVN7JWBBf68PWf4LVHXZSpzMdZOC0ENqmBRxD04d2PvBQJ1VO3Dh7p5SST6U5EC0/EQPxRjpQcuVhtx/IU3iVT1rVYjgtP88ryJ2wB6tarUJ8iLMAiC+xmn0wErDCp7yaxcqrNryfS1aC73IP5Dj9bm706o86QM6CS2j+PEmOo=,iv:78xHCnrCVFtFplQjF01xUC8LKKtYswbN/Ey48uraVug=,tag:pV8asUssOV0Y2Q0EuqfgTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
