apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:k6e/lOhAbu6htuL8xrZ5r6/9I6XI7laOKlTjgFsscJ78DuIAUIt3tcJ/PJFZzUYiSV6teJ0ys/nx4eMEuajQwd72/Ja449DZe5Gz,iv:19C/CIpNZe1xr09SUV22kf/Hpf5o6uGeF/6Wa30gD6w=,tag:5/fq4QQ/d1Wuy0ZFIkmLSg==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYlYvUXlLN3FzYnhGSEt2
        c2x3YjR1OXBtNCtaMDI1TkRMYzMrL0VBaEhzClNFWU0yVERwNW1aVyt4dkFsUm4y
        MHVkNWVGNnptNGlZa0pGaFlRTVlHS00KLS0tIEhROUJrck1zTnBuWTFQcDYwZEh3
        dFA1dFBKZWxQNDI1cXlKUmZDR2IvQUUKoI+sawhYjtd6+ZvgaJT1FnrrrdJR5ODw
        6ODCGF3ihgSKmzCLYB+6AsEjm0+Bt6gPLvpuA4zXefaWpa64mZ75Xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T20:51:05Z"
  mac: ENC[AES256_GCM,data:nfevxHi6+fJgYTD37Rmh9xqUtrIpDRjAvm2L9Ha1Zani7szLZHFV+2kbXAgcw4/kizv0YTwJO1FGTa44oCtmUPqM4Z7kXk1Pu/4753BNxbeTs3h1Zt9BozCT44StZiZljF1S9bFSKhmagGMAx3Unhgn+rJKe9nv7eiIqzHexhAQ=,iv:nyRdTuuAy+SK13vRactzz+WOxRm071mzSbXVqncg3Zc=,tag:y5AezFFwU96yQkxkfLuK9Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
