apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:SI0aFy1XKmjW4ihAG8IAvW2G9smAO42jRzVMPX+Hei2d4do9oyCL+r/QVC4LJPLGWZv3jBzgPfjFi8zpmr/4ls3+yszsd5pDjeYn,iv:F6r+ysTQIWonD8blrgOQ7P1KRX00Z8PAoJW7NYzk6KM=,tag:t0zoZTF8JPqPhDSad/OlRw==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxU0ExbmNHVWpidTlHYTZl
        T3RpTDhNdEpoNXdWSGZ0ZXVQN2lNM2ZGWmh3CjYwT2dsNkgwNGUvcFFqTTMydTlS
        UDlUcng0M3ZrWXp4aDBNbGo2U3lzZjgKLS0tIHAwYTR1RHo0aUZYbTJOUVUyZFRX
        Mi9BWDB4N1JBOS9QL0VYM0xWWjVrencKOsSO551sYA6b/8rET28lNKjxKHkp+fDa
        foxjugI45f0peN6FvuomLAQStKu8h3O+rkBCC+dadqsOxI+qgFqAEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-01T14:58:51Z"
  mac: ENC[AES256_GCM,data:pBToI7Bp7KLFDKYKgt4Ydz1ADPaCFasfbi0cT3RTelJtGEucM/ymKPWIZteMDDraCimS4MJE1lVnboiFOJGUydnBGJL9sMpoKigMXXFIBMIxNZxazLGdkdoalph3t3mPJxaUAXuObZ1b5r5CEUsyzSR6LEh3tJTf/OPCkU4bCY8=,iv:v8L9q7kr9BvsFQn/z1CFLRcRL6sXoUZSQMhzyP5JVjo=,tag:lCdlappmyCtqwuz/UV+Qqw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
