---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.20"
additionalMachineCertSans: *sans

clusterPodNets: ["10.69.0.0/16"]
clusterSvcNets: ["10.96.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "controller-3"
    ipAddress: "192.168.1.12"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/59fbc7cee4e5a568b633d98cd28c07dd27702fe8b7cad48868a977008f0f49f2
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e2:0d:fb:e0:ec:1f"
        dhcp: false
        addresses:
          - "192.168.1.12/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500
        vip:
          ip: "192.168.1.20"
  - hostname: "controller-4"
    ipAddress: "192.168.1.13"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/0f2e451d5c40999acbaf8df1d23f2e1f521cccf955d4defbcba6ffaca543a2ca
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b2:2a:c2:35:73:a9"
        dhcp: false
        addresses:
          - "192.168.1.13/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500
        vip:
          ip: "192.168.1.20"
  - hostname: "controller-1"
    ipAddress: "192.168.1.10"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/a25216969818193f030ffc088de38542752d5a2abf5108987db1f3f3e8f5e8e4
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b2:f8:cf:21:be:be"
        dhcp: false
        addresses:
          - "192.168.1.10/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500
        vip:
          ip: "192.168.1.20"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

