---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.20"
additionalMachineCertSans: *sans

clusterPodNets: ["10.69.0.0/16"]
clusterSvcNets: ["10.96.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "controller-1"
    ipAddress: "192.168.1.10"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4f0e9de2c7a093bfbe751be35b78c46fdbe713a6d886dc4190afaabb5ca16fd0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b2:f8:cf:21:be:be"
        dhcp: false
        addresses:
          - "192.168.1.10/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500
        vip:
          ip: "192.168.1.20"
  - hostname: "controller-3"
    ipAddress: "192.168.1.12"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/21673f307f6aa5382ee221fcda6aefb7ef05d1c46e104bac35f24a6a4964b4e5
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "e2:0d:fb:e0:ec:1f"
        dhcp: false
        addresses:
          - "192.168.1.12/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500
        vip:
          ip: "192.168.1.20"
  - hostname: "controller-4"
    ipAddress: "192.168.1.13"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/2e62da814c27518e6d74a8875e661dc4b4c359f3eadf1e7766a4d145089e228d
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "b2:2a:c2:35:73:a9"
        dhcp: false
        addresses:
          - "192.168.1.13/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500
        vip:
          ip: "192.168.1.20"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

