apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.11.x/deploy/longhorn.yaml
  - ./config
patches:
  - target:
      kind: ConfigMap
      name: longhorn-default-settings
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: longhorn-default-setting
      data:
        default-setting.yaml: |
          defaultDataPath: "/storage"