ingress:
  enabled: true
  host: longhorn2.gitlab.be
  ingressClassName: internal
service:
  ui:
    type: ClusterIP
defaultSettings:
  defaultDataPath: /var/mnt/storage
preUpgradeChecker:
  jobEnabled: false
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdGpGK3R6UHJWZG9tTzJK
        WUUzOWhCUzVUVlUrVEhrUEdrY2ZBdkhFZFdJCnRVRUlpSmZHcFo5ck9aKzhuRk0x
        RHR5SGNlTS9JdHJJeVVGeFg5bnNJNGMKLS0tIDYrUkhNUlRYK3dJTFFxZ0krUlZ0
        czhIN293S1FjSmVXQUwyQ3BEWUl6cVkK7DFF3k1lwbZlBjgH2gzmp05g9Dc1ppw5
        iLlAgBUB+GGf4LBppxN8RcacHgF9WLuzakg9+I5PQXSzR3Ti9dAZ9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T14:39:08Z"
  mac: ENC[AES256_GCM,data:1UHMu7h+MprkVOXNWbR1EzbmTTvyy5ukYw/TCBXlrhYiFwQtOyOmFjgvPJbsB/u3FWW5UE7PJBtH0IDPUG+7DAN1K0C8ThFven2as59Yf7aEHq5oHVksSwzw9g5S2kLVfJ+56X0P8bIJzNDxro0pWTzV38NrlLR2fwEA3VNkzg8=,iv:IkSFEPCdiFQ9kC5sZiQkeqFWACd8UmSUkqHypWIFv/0=,tag:DNEb+J5ASMUr4Kc5LoAAmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
