ingress:
  enabled: true
  host: longhorn2.gitlab.be
  ingressClassName: internal
service:
  ui:
    type: ClusterIP
defaultSettings:
  defaultDataPath: /var/mnt/storage
preUpgradeChecker:
  jobEnabled: false
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YUdBZEt4NUJVNXY0Y3JN
        YTFyYmZjQ2krYWVEeDlkeTN3WmF2Vkw3eVVVCjlTcUtDS2U4YzdrRDl0Ny93V0Jm
        NFNDc0wvc01QUVY5TVFqQnZDKzc1bDQKLS0tIGk4dHNTVkFHUlc2RDZGeUNINEhx
        UTB0aHJhS2hzVmJpbjlIL0NVS2pubWMKd5KZlfGfqJVZWLmn8hLjGcAxjwRVNANP
        rZ9FaM/6G85HlyXIHQl5MeE1E7p0oiK/A/M4OCh1cc6D3RDE4kZcEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T07:58:51Z"
  mac: ENC[AES256_GCM,data:/wvsvWNL95Wf4Q7/H1bO5jcns6mciyNgOCTpaOivn80dhC09QFxmn0MSBgTZbNhQ9McMnj6jo/z1tjAYT8+lTzBd4/WjRR7SeQSHssdoedN5C7ZlwJxwQWwyZynU3gZ/zXOgGafcYKbM2drPCTADVmDeblEFjGtXT2/cH+dxlEs=,iv:BlC3a4xZBQHpurUMs2AD/1lENg4sglWJdxUbUsABvGU=,tag:l6ysNvAT6r2e87TBslLZkA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
