ingress:
  enabled: true
  host: longhorn2.gitlab.be
  ingressClassName: internal
service:
  ui:
    type: ClusterIP
defaultSettings:
  defaultDataPath: /var/mnt/storage
preUpgradeChecker:
  jobEnabled: false
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRFpEUzN3a3J6VisrT1RT
        UHhCS2plWU5YUWdnZmk4NVh0ZXZoc284OGdVCjM3ZmFUOFpFczJkYURpamhUcTFv
        Ui93SnVBYitFUzdlcDd1WlNSYWY4eHcKLS0tIGdZZExTVTIwTkpvSDcxTDc2WUtX
        RHpac0NXM1Q0QkRSN1pZeks2SXFsMTQKMnjBOXUnp89BGBFzXktQLEObg0kBaqw6
        bVLYO6fOs54Z4vwYUMgGFdI3jqYF/0lSEJMnYiORfnkFlOwtMwt+UQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T14:23:54Z"
  mac: ENC[AES256_GCM,data:P9zega3DJKs966+7CqV+CYAhkIM+EKog6OY8THS+kpPA958i2LF3GHykhJeXQUySl9TKR7GbgRQfyUiCYxG6AJ7AVcVGVuXl3CBDu2idNQhGqQKiagcOqVtA8gDsb1po93g13IL4R46Jam/glK5FYpZuTk6mH5tqJfKqF+/Oap8=,iv:fPyUMLH91Tj3F1R0kCkQMJ2RrsS7pmFkkyTyU3yw+kI=,tag:EZ0iO90GgJUHOePJhqSH3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
