apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-configmap
data:
  config.yaml: ENC[AES256_GCM,data:3MkaGfnW2OcI5xDiqR8p9CkAYTqpgbNKcDXZwmQ1KpxZedvIY18SrwuVpl5xP5+CD+gQv5FdrVHMy0dKBlRi0GsmAsasP0t/HWlo7E9/dKRY9hqBwQX6ckU8F481pD2BsAqXO9HFiAXbADI+Oehoy/Eycv6ukOt0/qmXo8Yp8QVip1bU4d7raCyKAhITt+LexuPhBtnqunISAYVrXDyHaw7M7RT2nu5RhON+5eKnqwFp6hBwdvm216L5KhnjnOJkbPPg5DjfAaTvoRR21OMT1AQfSW9y1txLxwiXY3LajuPXvV/75ix4gWaKFKIBAw==,iv:OYAk8JrvdV2qQA8AmSOIaiuyteCzBnaEw+T8TDPy/to=,tag:BKpnb8UERRf5dTrQvv+aWw==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeXNjcnZ6N2J6aFZtYlNw
        Ymk0QzVsNi95emJIL2FYd0FxV2NFNEhaUUZFCkY0N0RzdzBOTVEvOG5ZdnJ6Sk1O
        YTFGR2JBbkRMaVJkRVRWVjc1b0M1NEUKLS0tIG1DV0IycmREVWlrcWtkaE5UbjhF
        L284N244VWxIODVJSjBmTmJBT2lZTFUKcRiZ05mOnW5YuyXTG1Gr6wWmMetOZ3rG
        /y1im3zL007Yq2+7bqykdaOeAZ7jIBm7UTXzOYLclFO4nj1eWs3wtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T15:04:51Z"
  mac: ENC[AES256_GCM,data:90/ulz1noCLq/l1Z5H3s0xl4AYt3Qq+zXropNamp0ID/8UhnpGrVTnQrJH/fUqgV4Ex4pofVtMY4AoXXZ3Rg/qoVi+yRWwIoZG+Ek7uXdB0qpbIHh/gPhFUrsRlcJQGAtX8stS1rLFcbO1hbY9xlw0gsyJIXTqMsX+skkZWdDEY=,iv:7Vx/gisyh18JDt+DR3VSpfTXSu8hyLLe0AnvXS289KY=,tag:3/dfvQixoFpwcK2tWa1GxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
