apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.gitlab.be
      recordType: CNAME
      targets:
        - 54580499-e05f-4728-9714-ada8c065e24e.cfargotunnel.com
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcytwSHpjY0h0bHNseGpZ
        cHdLeENoNTRRcC9wdXc5T3l3VmJicllFb1JRClBXUktuZTZMdlhZaFprOTRBMjBs
        TzFHbC9iZE1oMHcvNkZXVVJIZUM5ZWcKLS0tIC9tTWVabUhzWFpWN0Fybll0a3Ba
        WVlJanFIbDVzS3gyU3lyWVBCT2l6YVkKns9SlmjBQOWKBqWBcru6dGtxpYPWpcOb
        XXc+pavUfZjgZvs5YFrSUDFFKqIvXIcp5fWz3Qgq5owd7zr5cEu4zg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T08:27:20Z"
  mac: ENC[AES256_GCM,data:yajqkG8MOvMxngNLfKOPtTxoUx6+9XunbsUY7xVaXYKt4Su+HhRplc4ZDZf3GHe7T0rUkRhE288JosRlsJ6cYswhHogFsLtQWrLQJJNMmpnxvOa8xFAeLkKPykXtF7dH5MApqXhuRLcYXkOXaRgxz9L1it9cKPtZl1AMGyVfOrE=,iv:3ATnhmYbIC8dVkJkREJZHOGA7ny7Aybq87keUKOo/WY=,tag:Mu+01xJ4XNnpcDvf3f60oA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
