apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.gitlab.be
      recordType: CNAME
      targets:
        - 54580499-e05f-4728-9714-ada8c065e24e.cfargotunnel.com
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZU9TUEhQVXNad3lRdW1M
        cHlPVjVKZEt5ZnBQZW5vZXlVUjRCWW1QVmxzCkE5NVQ5R1czN0tUbDRkUHZHdmZn
        RlN3b1FsbWxYWDQzRHhIUFlpa2tXekEKLS0tIHlCdExnSjFCb3Y0bUNBRVVvUm5X
        YXVTcUFUaThNZXluT2NoMkl5elMyVU0KQk17cu/Mg/pdIn+Rsea4uGWJmEE9+rUM
        CL+HGR2MtNCXFNvECTGtAn3JMqxkmtKRmppb/8vUBY8ElpVNWxYgmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T15:43:44Z"
  mac: ENC[AES256_GCM,data:XvHWYo7N01Rhzgj/q69E6F0NV7eFnT2axUVMhKzSa5wwlrjQCw1uYxrBX5+xt5LyOpF0XjwzwFcKPnuqHPfZtvhhqC86f0DG9p7EN9yzT/MhrSJDPje8qlRszb9jd1GesIPUoPNxsOyNkRgcUvl705pbfKCxjmtqUipYey8+Xx8=,iv:FOatwzkRp/Ae9xytZTB+3KJjVPv/5RJrGrNZvuKsyj0=,tag:TvXdTrf8nAAunwFvebI+JA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
