apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.gitlab.be
      recordType: CNAME
      targets:
        - 54580499-e05f-4728-9714-ada8c065e24e.cfargotunnel.com
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U3I0S1FISUpTeCtUbk8w
        TVJ0UzZJbFY5UjFHUGxtL012bCtaL0hmSTNJCk44QjdPRWdBdmFQWE1SdElpa0dl
        TUJYK1FpNHZnMWdRTlM3dHdtSUsyQ1UKLS0tIHdwcUp0enBSMUlNSWlUSjhUR2R4
        WitLSUYwejZBMm9RM3UyTTZZMHZlNlkKdKof19T27A8KSzumttPnTsMPgO/iiQnB
        2cydK9TQpUR+s55TcOrNt8z/TeL1F6uhP2vWb2RiuDx7DX0EiIFDZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T14:39:08Z"
  mac: ENC[AES256_GCM,data:/aWgJVZCPgDzDi8u7iKdPdgOy4BgiiO1EsvFuIEtbt1GAl8E1gQI9FQPy75kC3toGPtC6wB1Bo1Uj+uasUznmi+Dif8MGM3s/lAZJh5m8heIFzvX0N7s9jQBoQxkyui6rL0waGjS4TDLXrjmWjiiyVoAyKWL6dFq32dVGOTloDA=,iv:AKQ+5BWd2EIgs9ORWp3PolY4DQ62l+X91jeNwEA+bRU=,tag:tX+WWHrB0mrV3ewD4NmIUw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
