apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:8AqZRCQ1Jnv/F+drSZXNshp4YFXze5upam6qIeRxjiUUQZO0AEMGdTPqiWbQM2wnitR9GzwXkb5+pU43Zrur6jVj2vOO+Kj4XTFzE5wnSoOIO1yAMpW+6Hs4dJTP37qfDQTtwQ2MIxmsdzQDe22b/FcuZX9Gkn4PHv+uHnCt1Fz4NhKuqVmQq3YS/JLM8muC6AE20nKseyJ2fY45eCWI730QVdHdBHqXkP3xCowET3nWvR4+,iv:QdNLm/l26O8K6PuMQpXkC8ss328WQzb5GBMRjX7iz5M=,tag:r1i+vshRXPy5IXt2QbCr3g==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TDlOTlBrOW1EckpzZHlN
        TW9obzBHWGRUWlZZTDJPWFFPRjFkdHQzMkNnCk80MEVSK1Z6OFNScHpEN0Zzd1I2
        dGd6WE05WnJ1cDZ5d0RPaGZyTkoyQ1EKLS0tIDluc3hWOVRtQUtMZ0habWNTdlE2
        UWhkd2laMnQ0T1RPanpmTXdKczJWbDQK72U8mjoxcBOH7HbaiQnXDNHW+zaP43j1
        sqB+dMG462us4wFCmm3KkCz0hTnD2DnTVFQ0ir13/U3/uaxBwrzJxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T20:00:43Z"
  mac: ENC[AES256_GCM,data:OAQD69veY2WOVkak26bAe+6ZYoQYiX2N7Ntwe620177uuQQa/oF03TD0mhoFN5hT9gIHPdvt5RkHW0LLzXV+mmbR0zkpS0b1bv7wBSLlj5BFyQOcxdGX+sb0aanoOG1Llvo6UZlXKZA76pmBte/uXT1iAlJYLHlORUXgvECwFtU=,iv:vwVhQdWyy1NZzDC5R8c6vs2Z48FwP0oB/+D2Sow5K7k=,tag:+4U2oY+jc2ENxNCpHp8N/A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
