apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:tw+l15CTtDtEfN6EOe0qFvjycvfZjMh2r7RW/Torr0oHyhE/1QEhG/hzqe2fMkLrhKCSwmC71prW9R+4JD8yZTAxRNYOYlwrZ47B8s+fY6gXFefwU7odA6EAWLpRlmbnvdwPPY10XDQYGER6fm+tuNHHFZppzPfnXMwbWnfUjCiKmAhBFVWtRDqAxpMw4BGxqpBfGWY5Jg60vxgF09tAOP14qnuAVszO7W5wviKh/QQ9g57i,iv:B5KwsC83hCeHcjs/72XlMizADKlrYGEPkPyklKUAG3A=,tag:utIKucc2liwrSEMedeZlbQ==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTeWx3NTludE0wVjlKczRl
        b3F0UWVNeldOUWRQYXJ5ZmJZdFVCN3I2eHhrCmJoZklFaFpGNFZ1UkcyNk13b2Iy
        NHdMNExzcW1hOGI2YmQ2Rm5pcnBzcWcKLS0tIEp0V3FYSnZoc2NqZ3ZxUVhPS3VF
        dW1UM3EzZUhXRkpzbHZUbllwRER3QUkKNY2FwsPssCAJg8+mM2anAZz4FR4SoU0b
        hzfo9r16Qh6EFXeRGV7AjYKqnYvPPjVs+ZYItModvHMF8J7bPwFyKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-01T13:13:36Z"
  mac: ENC[AES256_GCM,data:jdo6chOYjzpeW4PmvDRqD3yUPrOQrMVWN9Cs67gez4oWhz8KLBtlmIRSK9dOfXsC2IqOpBG1ifBawVdmgeQQm4oug3O34Ifv5aDPFE+4Paa19I/mFN+vszfe68cs3ue44C/Lcba1lSRskBXwcxcdXPprR763bYquDye7mJ/jKKQ=,iv:y5lylEzW2Vj+mjba9FKo7YHV85+pS2VRDOmaKZ1RUrA=,tag:pKEox3Q63ioRU0d9Oo0NmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
