apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:hyKyTxp+7xoUbZ8gBUtEvpsMbThjvxgaVy3dJQqaKvtJ0eoZxMbOZqJuufmre1zbDtPkZbL5WFCl3BZgCu4f5W1Jxk4knuTGq83wcvPrBi9O61js0xl8lpPMH7g918KHuKxPJ3/9Jy2h9eW00QawswgJTxSOyAcSNob1iTn4M9WtPGEQpa2Ue93q3mcxvjPUtD6leJBypIl015P5dyySa1PWmp5a2K46u4g6xebJyK7E83VY,iv:6e45iSP8qHX8IaUb/+b09xEqTVmq9cskLiNBCz2tlWQ=,tag:gKyERWzKW6PW9mRuF3A8Cw==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQStCendqbStrcnU5Tk9L
        T21HNi9xems3c0MxOWUwNGFkT1J3NFRtdzNvCml6QVRDLzBrMVd4MGZTZ0NNRSto
        aitYY0NaTVJKcnYzY1g3bExUVlk2MGcKLS0tIE9uVjc0dEJaR1JHSUszZ1lLSGNS
        RmJEQXhIUHU1YWV2YXBVQ1NqcTdmRTAKlO3p8IVu0l7WTlU1G4y9IgQ434mXRulq
        Hu817toANgpAl1/C4CVLOSVC41XmovjCSYevP0Mn6+0Rk0oir61aaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T14:44:19Z"
  mac: ENC[AES256_GCM,data:W+H9Mh21cuBW5NSfrNTETCQv8TW6tkfR04QtYUzJuNZa6lBnfF+QCMQYZQpEKKnX7ynfh+002zZ+sBYagrP0vPCVza+ExG0rt8AzSPEIAKBrPgoBSLB5uGNaF7E6VuXYYywCe6s2rUu4R+SU3ohkNp73cR1iFPgLZvFHS7MMnIg=,iv:WEIfm9D1iSmh8KdBCCSUlr0MdM0oB3DO1DxdyCp1Vxc=,tag:XC/W9W7NbKcIyltxWic7rg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
