fullnameOverride: k8s-gateway
domain: gitlab.be
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.22
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETFZLYmJ0Y3J6eXBjZjZ4
        VnZrTjlVMDlnQU1CVkY5UnI2TEo5QXJ4dUM0CnNWbXQrS3NicUNpZHpRS1UzT1Yy
        cTRyK2Z6dURwUXhFeHZGYUhtT0NMaUUKLS0tIDdZMTNDdnVaOG5wTU9qUGVCZzA5
        RkNtTGtBU1JYbThQejFSRWRLSnJCd1EKj6hXlIYJZlBKrG1cTLTDIQGvepQGgEwP
        hiB1C65/00g0ITSy+BIK5YKMn7PeBs7dMeNqXGoT6DM3HIlpGyBRTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T20:20:50Z"
  mac: ENC[AES256_GCM,data:BH5hLOWeKY5TK9ilJt1pjQXXCfkMj90k7B8U+R50Ep9cOs2MBAL1pRf7nLYpZPn5AJokbsi4SgQcIZXv3B6Eq8JJ5YszVj9yLiCYfAfKH7b0EsaboFQpMqiGhne7sCgFOU9I/P1xgH9hwBM3SNa+mBjrNQ7JgX6hirwUGD+q3pA=,iv:2/kuDbMAtFY1kFVkX9iWF7EqBgBj/vrpA/IadQg7uY0=,tag:QBVTrFfEQY09fEU9Vi9NvA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
