fullnameOverride: k8s-gateway
domain: gitlab.be
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.22
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadWVlZ3MwTUgzMDR1aWJ4
        alA2VGx3azdnN2Z2enpHWisvMjJZbWI3Z0JZCjFVQit3YTFnVGRCWWRQd3JZVEl3
        UERNMjdlblVjN3ZjWHNkanFoV0o0Z0UKLS0tIHJpNHMraENFRlp0SDl1VllpbWRa
        L0RTQVNrbStmTUdoL2N5RUpoc21nWk0KDrBc4i71NrHToLJ3egRP+ELq/FtwNiy7
        RVEBYXUZMhdKO1m66UhOzthqF+mEdYiJI5HKzDVe52eaQutq7wCFGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-06T19:02:47Z"
  mac: ENC[AES256_GCM,data:Yb441Jrctwy/RkLbFLfkriidmHK0JkHnqN9qBHeuWWktxEenNkQ4133Kh9/0pZc0B8is4EWzNcjg/tWW4+3AAU2QtVrJvlErruAvMMgkpYfS3cuzjuO+6JEyxmF7khFARoBrcGkeN3KHq4chosuoGSGP6G7O9FGS3vgcfACdUiY=,iv:yK3EIEWmU9hseTHC+4T8XNKiB+2cviybJCj+ypiZjX0=,tag:XiIfgtQjdFowfGz3LAIxsQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
