fullnameOverride: k8s-gateway
domain: gitlab.be
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 192.168.1.22
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNjMyU0w4SnV5aUg0MXRm
        UUpmMXcxOEhwRE9VdUQ4KzBoYVRuUmRMNXpNCkN6QVhLSGtWVVBESWNEbEJTWkRZ
        UzJDaGZpcExUQXhvdjlOckNUWjZERjAKLS0tIEpJZXFYWE5ZVmR5UG9CbFlTcTla
        KzZKSVp1a2JlTUNZa01aclFIQmpXSTgKIB4Xa3mFbpqrcvjee3YBPliAERNJhiR8
        1ks/YhSZA6z83e3cYxqBKf/g+lyG9z+hnMcmaiAxM2wYPC5ETDMYgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T06:32:46Z"
  mac: ENC[AES256_GCM,data:bDI8B4Nsg4cr7UXre8CxO8epwXPQ4NlgSFTEUIVdCg5z4Dlt4yaqkVcsdmc9BYbaivC6Uj0fdbtiRhrwtbyzagS0ph6+sjy5HP/y9eAtPkFj4m2DB7WmG9WKJAQVs7We8Wh166DyK/8O0YDLTc2EgLVoxrsTgcywzwI08FoNhjM=,iv:j6ARHKQ7H66db/FIY51eLEzWMBT/HP7eMWCF06JirB4=,tag:MlR9xzcvxoDRGGknO9dMyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
