apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:UIY1h67hBUWk5kWTQoBroI+ekgLwvBJecdtaxpDEuYbXzRrif1A6PQ==,iv:8ebMmSJwe/wS/Vyt+G+b6GNE86XFBmqpi/gdKOshBys=,tag:c9VLk5A6wwRFsLxj2z/qCg==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMHhSMUtyb2llZDVuMjE0
        TzNYWEdGUkkvWFQvK1ZsTUFUSzNnaXZvR1hRCmQ0TlRwMFFJRmFWVEdwZ3dST1BU
        TzhZaGRNRWxNM2JNNHpkM3lmTWt1azAKLS0tIHdpeGppbE1YTXVwK2t5YmdqYnFn
        MHNwWVg5VTMzc1V4emVWSk12OGd1V1kKkkAjQrpSkGjiUE2Ws20nftD4v1YNdX/s
        /mx1hSy+7qmQzfBdgXylIVzdu4Pa/l9X/gGn/y4r+gFMj3JEtiK7tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T21:10:42Z"
  mac: ENC[AES256_GCM,data:i5f0Un90so+7ko4xng4TEFdOup/aBcXP1EhQ8oL0mkNxmrTQMkdx6bGrcGXQ1U3U5+xPrnUN6/hQjlImi2Bz9ogNmcmur9DYMR2srTYeFGtvCFUXDewouBiaEpbp5i0z2yuOnkYJo/6ggXhZ+9jtc9Gc+ApOql9K412XLpv0zCw=,iv:ZZOo28PdockgM5sInxq1qH78Z861UxjSI5RqN1035F8=,tag:fPy4ou7Vyk3cf0nwRmakow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
