apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:OzbyiKgHFKG8m0Ycq2baObndq5H659VzaQnY6X99RqjxzjvCcYKmRQ==,iv:ZEZ+QdYFV7Hclce4bIpmalWk6Mx1bc/kHHzWosnV6PY=,tag:7t650z5hES8jTnLS/2rFPA==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQzZOcXAyaWVmTFUvcXpR
        U2x0eFRrNk83VVJkdHRMT0lRR2hzcTJ6MmhZCkRzN2toRUtnTjk5Y0piZHVoRitn
        TmRnS3VMMzNJcDBBVG96M1dmemR1OTQKLS0tIEhrVk93VmtnMEQrWUVXdGhJTnNt
        VnllOEhPN3RIRlpyZmJHcHNUZGdqcTAKMkRt7xfVhjdEqumLwTws3gJpMHx3DPcW
        anYGSZgKo60FoPJIESiTxxAbrS/UhnanKDrL9O3u/Uc3+GZ/TZ9CTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-09T17:03:30Z"
  mac: ENC[AES256_GCM,data:cY769c272UUwpyaOiQLSrB71/5f0a1munirJ5tJCsj0wOraqABiFj0QgoccYk7JrikAhPiPSLkSYR+CDlVwtkj7j9kRatuDC91H5n8M8BVGIGQocJ1umhIO2FNxqImTUy6jYti1gaHsi+f7/oDvxXAHNePWRBb4nKAZt8x64L7Y=,iv:KhTwC+b/PsQ4ADzNGi4szcQMs/uoVLQLVUOTNZ575K0=,tag:wM3Qcmwu1JTY55yprGzLJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
