apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:LGpvkLf1fkunaa7HOcn2DdnShaHZYMcW02Yp09eX2uywM+gGBm9nJQ==,iv:FfcTuudmlJeUPcw/8N2P3dsG6VB/e29opaZwa5B3Ipk=,tag:SPHaHJ8TXd8SiE8UqT2xNw==,type:str]
sops:
  age:
    - recipient: age1086gtxn8l9dh0t2y0nu5ye0hczjyjc7q5tengjcf8lkynlta653sapg96f
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV3Y4OTlyaGNiTkJiQnBB
        NnhjK05DMStwTWFhTzBGM1prYUFMS1NXRTNVCkk2aVphKzRUUEI2c3g2amlBVmhN
        bUdETVdZd1NuMmtrMTV1NFZKb3RZMVEKLS0tIFkzV1VxMnBVdkJ3a2VUVThHUWtr
        cEZGSzdhbDFuYVVPem02OVFDQlZMbEUK0YSPrNl4uVQfsBuMz/NnIaVwVLYKf+/X
        Zg4ftt3cAh6/Aj3Ait8B3qTu7akAWlAis6nvHVm8y9yB0gii8aOu5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-07T07:19:39Z"
  mac: ENC[AES256_GCM,data:pgT8bTbj3AQ5DuCXznNGpluzFCMPSJ4sTuXSX5YuUl4kYbZxPJJO17j3W34tHsf0A993BnkYnfZrC1GkQfOrwhvTKXSxcMrwcpcAZcVgn9KTF806MU5GwhurPjc7gGu41CSp+4+IrNRAqaJbx5SbWN6sHiUUrXYdwGIirumTA54=,iv:l98ALaYZr1dhNc2iUn5RrXk3XNuvM2OsTPts63WIgTo=,tag:3mowwYtgTYOO3Q6C9GyaSg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
